Repository rolling-scopes/site, pull requests merged in 2024-07, with the labels that each got.

#369 365-feat: Add restrict default exports ESLint rule
  eslint.config.js
Labels: preview

#362 360-fix: change normalize.scss import priority
  src/app/styles/index.scss
  src/app/styles/normalize.scss
  vite.config.ts
Labels: preview

#350 348-refactor: Title component refactor
  eslint.config.js
  package-lock.json
  package.json
  src/app/layouts/base-layout/components/partnered/partnered.tsx
  src/app/styles/index.scss
  src/app/styles/normalize.scss
  src/entities/courses/ui/general/general.tsx
  src/entities/courses/ui/main/main.tsx
  src/shared/ui/main-title/index.ts
  src/shared/ui/main-title/main-title.module.scss
  src/shared/ui/main-title/main-title.test.tsx
  src/shared/ui/main-title/main-title.tsx
  src/shared/ui/title/index.ts
  src/shared/ui/title/title.scss
  src/shared/ui/title/title.test.tsx
  src/shared/ui/title/title.tsx
  src/shared/ui/title/types.ts
  src/shared/ui/widget-title/index.ts
  src/shared/ui/widget-title/widget-title.module.scss
  src/shared/ui/widget-title/widget-title.test.tsx
  src/shared/ui/widget-title/widget-title.tsx
  src/widgets/about-home/ui/about.tsx
  src/widgets/about-school/ui/about.tsx
  src/widgets/about-video/ui/about-video.tsx
  src/widgets/about/ui/about.tsx
  src/widgets/about/ui/info-grid/info-grid.scss
  src/widgets/alumni/ui/alumni.tsx
  src/widgets/angular-topics/ui/angular-topics.tsx
  src/widgets/certification/ui/certification.tsx
  src/widgets/communication/ui/communication.tsx
  src/widgets/community/ui/community.tsx
  src/widgets/contribute/ui/contribute.tsx
  src/widgets/course-main/course-main.tsx
  src/widgets/courses-school/ui/courses.module.scss
  src/widgets/courses-school/ui/courses.tsx
  src/widgets/courses/ui/courses.tsx
  src/widgets/events/ui/events.tsx
  src/widgets/faq/ui/faq.tsx
  src/widgets/main/ui/main.scss
  src/widgets/main/ui/main.tsx
  src/widgets/mentoring/ui/mentoring.tsx
  src/widgets/mentors-wanted/ui/mentors-wanted.tsx
  src/widgets/mentors/ui/mentors.tsx
  src/widgets/merch/ui/merch.tsx
  src/widgets/numbers/ui/numbers.tsx
  src/widgets/pictures/ui/pictures.tsx
  src/widgets/principles/ui/principle-card/principles.tsx
  src/widgets/required/ui/required.tsx
  src/widgets/speakers/ui/speakers.tsx
  src/widgets/study-path/ui/study-path.tsx
  src/widgets/study-with-us/ui/study-with-us.tsx
  src/widgets/support/ui/support.tsx
  src/widgets/trainers/ui/trainers.tsx
  src/widgets/training-program/ui/training-program.tsx
Labels: preview

#377 364-fix: Add mentors to js front-end courses pages
  src/pages/javascript-ru.tsx
  src/widgets/trainers/javascript-ru.data.ts
Labels: preview

#380 379 - chore: configure dependabot to keep track of github actions
  .github/dependabot.yml
Labels: feature

#354 320-feat: add FSD eslint config
  eslint.config.js
  package-lock.json
  package.json
Labels: feature, high priority

#386 385-fix: Remove unused font
  index.html
Labels: preview

#387 359 - chore: configure coderabbit ai
  .coderabbit.yaml
Labels: feature

#366 250-refactor: add robot.txt, meta tag with description
  index.html
  public/robots.txt
Labels: preview

#399 398-chore: modify codeowners
  .github/CODEOWNERS
Labels: refactor, high priority

#407 402-refactor: day.js impotrs refactored
  src/main.tsx
  src/shared/helpers/dayJS.ts
  src/shared/helpers/getActualDataList.test.ts
  src/shared/helpers/getActualDataList.ts
  src/widgets/course-main/course-main.test.tsx
Labels: preview

#406 403-fix : React key error is fixed
  src/widgets/required/ui/required.tsx
  src/widgets/trainers/ui/trainers.tsx
Labels: bug, preview

#409 285-fix: different course days
  src/widgets/courses-school/courses.test.tsx
  src/widgets/courses-school/lib/selectCourses.ts
  src/widgets/courses-school/model/constants.ts
  src/widgets/courses-school/ui/courses.tsx
Labels: preview

#388 376-refactor: Section-label component refactor
  src/shared/ui/section-label/section-label.module.scss
  src/shared/ui/section-label/section-label.test.tsx
  src/shared/ui/section-label/section-label.tsx
  src/widgets/course-main/course-main.tsx
  src/widgets/events/ui/events.tsx
  src/widgets/merch/ui/merch.tsx
  src/widgets/study-with-us/ui/study-with-us.tsx
Labels: refactor, preview

#414 413-refactor: update registration details for upcoming courses
  src/app/services/data/courses.data.ts
Labels: preview

#422 420-fix: Disable embedding of svg images into js bundle
  vite.config.ts
Labels: bug, preview

#417 416-chore: Extend qodana config
  .github/workflows/code-quality.yml
Labels: feature, preview

#424 423-fix: Add ESLint rules for formatting import-export long strings
  .vscode/settings.json
  eslint.config.js
  package-lock.json
  package.json
  src/app/layouts/base-layout/components/scroll-to-hash/scroll-to-hash.test.tsx
  src/app/services/api/index.ts
  src/shared/hooks/use-data-by-name/use-data-by-name.ts
  src/shared/hooks/use-title/use-title.test.tsx
  src/shared/ui/image/utils/convertToWebp.ts
  src/shared/ui/widget-title/widget-title.tsx
  src/widgets/about/about.data.ts
  src/widgets/community/ui/community.tsx
  src/widgets/courses-school/courses.test.tsx
  src/widgets/courses/ui/courses.tsx
  src/widgets/requirements/ui/requirements.tsx
  src/widgets/study-path/ui/stages/stages.tsx
Labels: preview

#418 264-fix: Fix image errors on small screens
  optimizeImages/optimizeImages.js
Labels: bug, preview

#428 427-fix: Fix regex in pre-push hook
  .husky/pre-push
Labels: bug, high priority

#432 431-fix: Correct behavior of husky precommit
  .husky/pre-commit
  .husky/prepare-commit-msg
  package.json
Labels: preview
