Repository rolling-scopes/site, pull requests merged in 2024-12, with the labels that each got.

#674 641-fix: Course icon
  src/entities/course/ui/course-card/course-card.module.scss
Labels: bug

#679 678-feat: Update corse link
  dev-data/courses.data.ts
Labels: high priority

#675 614-fix: Pre school subtitle
  dev-data/about-course.data.tsx
  dev-data/courses.data.ts
  src/app/courses/javascript-preschool-ru/page.tsx
  src/entities/course/types.ts
  src/shared/__tests__/constants.ts
  src/shared/helpers/getActualData.test.ts
  src/views/javascript-preschool-ru.tsx
  src/views/javascript-ru.tsx
  src/widgets/about-course/ui/about-course/about-course.test.tsx
  src/widgets/about-course/ui/about-course/about-course.tsx
  src/widgets/hero-course/ui/hero-course.test.tsx
  src/widgets/hero-course/ui/hero-course.tsx
  src/widgets/training-program/ui/training-program.test.tsx
Labels: bug, preview

#667 556-feat: Widget not found
  src/app/[...mentorship]/page.tsx
  src/app/mentorship/[course]/page.tsx
  src/app/mentorship/page.tsx
  src/app/not-found.tsx
  src/shared/__tests__/visual/not-found.spec.ts
  src/views/not-found.tsx
  src/views/not-found/not-found.module.scss
  src/views/not-found/not-found.tsx
  src/widgets/not-found/index.ts
  src/widgets/not-found/ui/not-found.scss
  src/widgets/not-found/ui/not-found.tsx
Labels: refactor, preview

#655 480-refactor: Remove css prefixes
  src/entities/event/ui/event-card/event-card.module.scss
  src/entities/event/ui/event-card/event-card.tsx
Labels: preview

#671 669-fix: Deprication warnings in tests
  package-lock.json
  package.json
  vitest.config.ts
Labels: preview

#684 567-refactor: Widget support
  src/widgets/support/support.test.tsx
  src/widgets/support/ui/support.module.scss
  src/widgets/support/ui/support.test.tsx
  src/widgets/support/ui/support.tsx
Labels: refactor, preview

#659 563-refactor: Widget school menu
  dev-data/index.ts
  dev-data/school-menu-links.ts
  src/core/base-layout/components/footer/desktop-view.tsx
  src/core/base-layout/components/header/header.module.scss
  src/core/base-layout/components/header/header.tsx
  src/core/base-layout/components/header/nav-item/nav-item.tsx
  src/core/const/index.ts
  src/shared/__tests__/visual/main.spec.ts
  src/widgets/mobile-view/ui/mobile-view.tsx
  src/widgets/school-menu/index.ts
  src/widgets/school-menu/school-menu.test.tsx
  src/widgets/school-menu/types.ts
  src/widgets/school-menu/ui/school-item/school-item.module.scss
  src/widgets/school-menu/ui/school-item/school-item.tsx
  src/widgets/school-menu/ui/school-list/school-list.tsx
  src/widgets/school-menu/ui/school-menu.scss
  src/widgets/school-menu/ui/school-menu.tsx
  src/widgets/school-menu/ui/school-menu/school-menu.module.scss
  src/widgets/school-menu/ui/school-menu/school-menu.test.tsx
  src/widgets/school-menu/ui/school-menu/school-menu.tsx
Labels: refactor, high priority, preview

#692 691-feat: Update node registration link
  dev-data/courses.data.ts
Labels: preview

#668 564-refactor: Widget speakers
  src/shared/constants.ts
  src/shared/icons/email.tsx
  src/shared/icons/index.tsx
  src/widgets/speakers/ui/speakers.module.scss
  src/widgets/speakers/ui/speakers.scss
  src/widgets/speakers/ui/speakers.test.tsx
  src/widgets/speakers/ui/speakers.tsx
Labels: refactor, high priority, preview

#661 569-refactor: Widget training program
  dev-data/index.ts
  dev-data/training-program.data.tsx
  src/widgets/training-program/ui/training-program.module.scss
  src/widgets/training-program/ui/training-program.scss
  src/widgets/training-program/ui/training-program.test.tsx
  src/widgets/training-program/ui/training-program.tsx
Labels: refactor, high priority, preview

#662 559-refactor: Widget places
  package-lock.json
  package.json
  src/widgets/places/constants.ts
  src/widgets/places/index.ts
  src/widgets/places/places.test.tsx
  src/widgets/places/ui/marquee-group/marquee-group.module.scss
  src/widgets/places/ui/marquee-group/marquee-group.tsx
  src/widgets/places/ui/place-item/place-item.module.scss
  src/widgets/places/ui/place-item/place-item.tsx
  src/widgets/places/ui/places.scss
  src/widgets/places/ui/places.tsx
  src/widgets/places/ui/places/places.module.scss
  src/widgets/places/ui/places/places.test.tsx
  src/widgets/places/ui/places/places.tsx
Labels: refactor, high priority, preview

#697 696-fix: Speakers wanted layout issue
  src/widgets/speakers/ui/speakers.module.scss
Labels: preview

#670 551-refactor: Fsd widget merch
  dev-data/index.ts
  dev-data/merch.data.ts
  src/shared/__tests__/constants.ts
  src/widgets/merch/merch.test.tsx
  src/widgets/merch/ui/merch.module.scss
  src/widgets/merch/ui/merch.test.tsx
  src/widgets/merch/ui/merch.tsx
Labels: preview

#700 699-feat: Rs app course integration improvements
  dev-data/courses.data.ts
  src/entities/course/helpers/sync-with-api-data.test.ts
  src/entities/course/helpers/sync-with-api-data.ts
  src/entities/course/types.ts
  src/shared/__tests__/constants.ts
  src/shared/constants.ts
  src/shared/helpers/getActualData.test.ts
  src/widgets/about-course/ui/about-course/about-course.test.tsx
  src/widgets/hero-course/ui/hero-course.test.tsx
Labels: feature, preview

#695 694-refactor: Widget general
  dev-data/general.data.ts
  dev-data/index.ts
  src/widgets/general/general.scss
  src/widgets/general/general.tsx
  src/widgets/general/index.ts
  src/widgets/general/ui/general.module.scss
  src/widgets/general/ui/general.test.tsx
  src/widgets/general/ui/general.tsx
Labels: refactor, high priority, preview

#690 689-fix: Style issues
  src/widgets/about-community/ui/about-community.tsx
  src/widgets/mentors-wanted/ui/mentors-wanted.module.scss
Labels: bug, preview
