Repository rolling-scopes/site, pull requests merged in 2024-08, with the labels that each got.

#415 400-refactor: Helper function getActualDataList
  src/shared/helpers/getActualData.test.ts
  src/shared/helpers/getActualData.ts
  src/shared/helpers/getActualDataList.ts
  src/widgets/courses-school/ui/courses.tsx
  src/widgets/courses/ui/courses.tsx
  src/widgets/events/ui/events.tsx
Labels: preview

#433 313-fix: Correct display of partner icons
  src/app/layouts/base-layout/components/partnered/partnered.scss
  src/app/layouts/base-layout/components/partnered/partnered.tsx
Labels: preview

#429 425-refactor: WidgetTitle and MainTitle refactor
  src/shared/__tests__/visualTesting/community.spec.ts-snapshots/community-Mobile-Chrome-darwin.png
  src/shared/__tests__/visualTesting/community.spec.ts-snapshots/community-Mobile-Safari-darwin.png
  src/shared/__tests__/visualTesting/community.spec.ts-snapshots/community-chromium-darwin.png
  src/shared/__tests__/visualTesting/community.spec.ts-snapshots/community-firefox-darwin.png
  src/shared/__tests__/visualTesting/community.spec.ts-snapshots/community-webkit-darwin.png
  src/shared/__tests__/visualTesting/courses.spec.ts-snapshots/courses-Mobile-Chrome-darwin.png
  src/shared/__tests__/visualTesting/courses.spec.ts-snapshots/courses-Mobile-Safari-darwin.png
  src/shared/__tests__/visualTesting/courses.spec.ts-snapshots/courses-chromium-darwin.png
  src/shared/__tests__/visualTesting/courses.spec.ts-snapshots/courses-firefox-darwin.png
  src/shared/__tests__/visualTesting/courses.spec.ts-snapshots/courses-webkit-darwin.png
  src/shared/__tests__/visualTesting/main.spec.ts-snapshots/main-Mobile-Chrome-darwin.png
  src/shared/__tests__/visualTesting/main.spec.ts-snapshots/main-Mobile-Safari-darwin.png
  src/shared/__tests__/visualTesting/main.spec.ts-snapshots/main-chromium-darwin.png
  src/shared/__tests__/visualTesting/main.spec.ts-snapshots/main-firefox-darwin.png
  src/shared/__tests__/visualTesting/main.spec.ts-snapshots/main-webkit-darwin.png
  src/shared/__tests__/visualTesting/report/index.html
  src/shared/ui/main-title/main-title.module.scss
  src/shared/ui/main-title/main-title.test.tsx
  src/shared/ui/main-title/main-title.tsx
  src/shared/ui/widget-title/widget-title.module.scss
  src/shared/ui/widget-title/widget-title.test.tsx
  src/shared/ui/widget-title/widget-title.tsx
  src/widgets/about-home/ui/about.tsx
  src/widgets/about-school/ui/about.tsx
  src/widgets/about-video/ui/about-video.tsx
  src/widgets/about/ui/about.tsx
  src/widgets/alumni/ui/alumni.tsx
  src/widgets/angular-topics/ui/angular-topics.tsx
  src/widgets/certification/ui/certification.tsx
  src/widgets/communication/ui/communication.tsx
  src/widgets/contribute/ui/contribute.tsx
  src/widgets/course-main/course-main.tsx
  src/widgets/courses/ui/courses.tsx
  src/widgets/events/ui/events.tsx
  src/widgets/faq/ui/faq.tsx
  src/widgets/mentors-wanted/ui/mentors-wanted.tsx
  src/widgets/merch/ui/merch.tsx
  src/widgets/numbers/ui/numbers.tsx
  src/widgets/pictures/ui/pictures.tsx
  src/widgets/required/ui/required.tsx
  src/widgets/study-with-us/ui/study-with-us.tsx
  src/widgets/trainers/ui/trainers.tsx
  src/widgets/training-program/ui/training-program.tsx
Labels: refactor, preview

#419 368-refactor: Change logo wrapper component for FSD
  src/app/layouts/base-layout/components/footer/about-list.tsx
  src/app/layouts/base-layout/components/footer/footer.test.tsx
  src/app/layouts/base-layout/components/header/header.test.tsx
  src/app/layouts/base-layout/components/header/header.tsx
  src/shared/icons/index.tsx
  src/shared/icons/logo.tsx
  src/shared/ui/logo-wrapper/index.ts
  src/shared/ui/logo-wrapper/logo-wrapper.tsx
  src/shared/ui/logo/index.ts
  src/shared/ui/logo/logo.module.scss
  src/shared/ui/logo/logo.test.tsx
  src/shared/ui/logo/logo.tsx
  src/widgets/mobile-view/ui/mobile-view.tsx
Labels: preview, testing

#456 455-chore: remove qodana scan from CI
  .github/workflows/code-quality.yml
Labels: refactor

#442 441-refactor: Change section label tag
  src/shared/ui/section-label/section-label.tsx
  src/widgets/about-home/ui/about.tsx
Labels: refactor, preview, testing

#454 268-feat: Rework mobile menu
  src/app/layouts/base-layout/components/footer/footer.test.tsx
  src/widgets/mobile-view/ui/mobile-view.module.scss
  src/widgets/mobile-view/ui/mobile-view.scss
  src/widgets/mobile-view/ui/mobile-view.tsx
Labels: preview

#453 452-refactor: Image component refactor
  src/entities/courses/ui/course-card/course-card.tsx
  src/entities/courses/ui/main/main.tsx
  src/shared/constants.ts
  src/shared/helpers/convertToWebp.ts
  src/shared/helpers/generateSizes.ts
  src/shared/helpers/generateSrcSet.ts
  src/shared/icons/angular-icon.tsx
  src/shared/icons/arrow-icon.tsx
  src/shared/icons/aws.tsx
  src/shared/icons/discord-logo.tsx
  src/shared/icons/dropdown-arrow.tsx
  src/shared/icons/email.tsx
  src/shared/icons/epam.tsx
  src/shared/icons/facebook.tsx
  src/shared/icons/github.tsx
  src/shared/icons/html-icon.tsx
  src/shared/icons/instagram.tsx
  src/shared/icons/javascript-icon.tsx
  src/shared/icons/jetbrains.tsx
  src/shared/icons/linkedIn.tsx
  src/shared/icons/nodejs-icon.tsx
  src/shared/icons/open-source-philosophy-icon.tsx
  src/shared/icons/open-to-everyone-icon.tsx
  src/shared/icons/react-icon.tsx
  src/shared/icons/rs-banner.tsx
  src/shared/icons/teach-It-forward-icon.tsx
  src/shared/icons/telegram.tsx
  src/shared/icons/text-link-icon.tsx
  src/shared/icons/youtube.tsx
  src/shared/ui/date-lang/date-lang.tsx
  src/shared/ui/image/image.test.tsx
  src/shared/ui/image/image.tsx
  src/shared/ui/image/index.ts
  src/shared/ui/image/types.ts
  src/shared/ui/logo/logo.tsx
  src/widgets/about-home/ui/about.tsx
  src/widgets/about/ui/info-grid/info-grid.tsx
  src/widgets/alumni/ui/alumni.tsx
  src/widgets/community/ui/community.tsx
  src/widgets/contribute/ui/contribute.tsx
  src/widgets/course-main/course-main.tsx
  src/widgets/courses-school/ui/CourseCard.tsx
  src/widgets/events/ui/events.tsx
  src/widgets/mentors-wanted/ui/mentors-wanted.tsx
  src/widgets/mentors/ui/mentors.tsx
  src/widgets/merch/ui/merch.tsx
  src/widgets/not-found/ui/not-found.tsx
  src/widgets/numbers/ui/numbers.tsx
  src/widgets/pictures/ui/pictures.tsx
  src/widgets/school-menu/ui/school-item/school-item.tsx
  src/widgets/speakers/ui/speakers.tsx
  src/widgets/study-path/ui/stage-card/image/image.tsx
  src/widgets/study-path/ui/stage-card/logo-icon/logo-icon.tsx
  src/widgets/study-with-us/ui/study-with-us.tsx
  src/widgets/support/ui/support.tsx
  src/widgets/trainers/ui/trainers-card/trainer-card.tsx
  src/widgets/training-program/ui/training-program.tsx
Labels: refactor, preview

#396 370-refactor: Link-custom component refactor
  src/entities/courses/ui/course-card/course-card.tsx
  src/entities/events/ui/event-card/event-card.tsx
  src/shared/ui/link-custom/link-custom.module.scss
  src/shared/ui/link-custom/link-custom.test.tsx
  src/shared/ui/link-custom/link-custom.tsx
  src/widgets/about/ui/about.tsx
  src/widgets/course-main/course-main.tsx
  src/widgets/courses-school/ui/CourseCard.tsx
  src/widgets/courses-school/ui/courses.module.scss
  src/widgets/courses-school/ui/courses.tsx
  src/widgets/mentors/ui/mentors.tsx
  src/widgets/merch/ui/merch.tsx
  src/widgets/not-found/ui/not-found.tsx
  src/widgets/option-item/ui/option-item.scss
  src/widgets/option-item/ui/option-item.tsx
  src/widgets/requirements/ui/requirements.tsx
  src/widgets/support/ui/support.scss
  src/widgets/support/ui/support.tsx
  src/widgets/training-program/ui/training-program.tsx
Labels: draft, preview

#463 462-feat: Update trainers jsfe ru
  src/shared/assets/mentors/Vitalii-Rogozin.png
  src/shared/assets/mentors/m-golubeva.webp
  src/shared/assets/mentors/m-oleinik.webp
  src/shared/assets/mentors/v-rogozin.webp
  src/shared/assets/mentors/y-kursevich.webp
  src/widgets/trainers/javascript-ru.data.ts
  src/widgets/trainers/preSchool.data.ts
Labels: preview

#469 458-fix: Nav item drops active state
  src/app/layouts/base-layout/components/header/nav-item/nav-item.tsx
Labels: preview
