Repository rolling-scopes/site, pull requests merged in 2024-09, with the labels that each got.

#447 430-refactor: Actions component refactor
  src/app/services/data/angular-path.data.ts
  src/app/services/data/aws-dev-path.data.ts
  src/app/services/data/courses-data.types.ts
  src/app/services/data/js-path.data.ts
  src/app/services/data/js-ru-path.data.ts
  src/entities/courses/ui/general/general.scss
  src/entities/courses/ui/general/general.tsx
  src/pages/javascript-en.tsx
  src/shared/__tests__/visualTesting/community.spec.ts-snapshots/community-Mobile-Chrome-darwin.png
  src/shared/__tests__/visualTesting/community.spec.ts-snapshots/community-Mobile-Safari-darwin.png
  src/shared/__tests__/visualTesting/community.spec.ts-snapshots/community-chromium-darwin.png
  src/shared/__tests__/visualTesting/community.spec.ts-snapshots/community-firefox-darwin.png
  src/shared/__tests__/visualTesting/community.spec.ts-snapshots/community-webkit-darwin.png
  src/shared/__tests__/visualTesting/courses.spec.ts-snapshots/courses-Mobile-Chrome-darwin.png
  src/shared/__tests__/visualTesting/courses.spec.ts-snapshots/courses-Mobile-Safari-darwin.png
  src/shared/__tests__/visualTesting/courses.spec.ts-snapshots/courses-chromium-darwin.png
  src/shared/__tests__/visualTesting/courses.spec.ts-snapshots/courses-firefox-darwin.png
  src/shared/__tests__/visualTesting/courses.spec.ts-snapshots/courses-webkit-darwin.png
  src/shared/__tests__/visualTesting/main.spec.ts-snapshots/main-Mobile-Chrome-darwin.png
  src/shared/__tests__/visualTesting/main.spec.ts-snapshots/main-Mobile-Safari-darwin.png
  src/shared/__tests__/visualTesting/main.spec.ts-snapshots/main-chromium-darwin.png
  src/shared/__tests__/visualTesting/main.spec.ts-snapshots/main-firefox-darwin.png
  src/shared/__tests__/visualTesting/main.spec.ts-snapshots/main-webkit-darwin.png
  src/shared/hooks/use-data-by-name/use-data-by-name.test.ts
  src/shared/ui/actions/actions.scss
  src/shared/ui/actions/actions.test.tsx
  src/shared/ui/actions/actions.tsx
  src/shared/ui/list/index.ts
  src/shared/ui/list/list.module.scss
  src/shared/ui/list/list.test.tsx
  src/shared/ui/list/list.tsx
  src/widgets/angular-topics/ui/angular-topics.tsx
  src/widgets/required/ui/required.tsx
  src/widgets/requirements/requirements.test.tsx
  src/widgets/requirements/ui/requirements.scss
  src/widgets/requirements/ui/requirements.tsx
  src/widgets/study-path/study-path.test.tsx
  src/widgets/study-path/ui/stage-card/actions/actions.test.tsx
  src/widgets/study-path/ui/stage-card/actions/actions.tsx
  src/widgets/study-path/ui/stage-card/actions/index.ts
  src/widgets/study-path/ui/stage-card/stage-card.tsx
  src/widgets/study-path/ui/stage-card/stage-card.types.ts
  src/widgets/study-path/ui/stages/stages.test.tsx
  src/widgets/study-path/ui/stages/stages.tsx
  src/widgets/training-program/training-program.data.tsx
Labels: refactor, preview

#485 481-feat: Add aws devops course page
  src/app/const/index.ts
  src/app/routes.tsx
  src/app/services/data/courses-path.data.ts
  src/app/services/data/courses.data.ts
  src/pages/aws-devops.tsx
  src/shared/assets/mentors/a-khatseyeva.webp
  src/shared/data/communication.data.ts
  src/shared/data/courseTitles.data.ts
  src/widgets/about/about.data.ts
  src/widgets/about/ui/about.tsx
  src/widgets/breadcrumbs/constants.ts
  src/widgets/required/required.data.ts
  src/widgets/required/required.types.ts
  src/widgets/school-menu/ui/school-menu.scss
  src/widgets/trainers/awsDevops.ts
  src/widgets/training-program/training-program.data.tsx
Labels: preview

#461 459-fix: Display logo
  src/app/layouts/base-layout/components/footer/about-list.tsx
  src/app/layouts/base-layout/components/header/header.tsx
  src/shared/ui/logo/logo.module.scss
  src/shared/ui/logo/logo.test.tsx
  src/shared/ui/logo/logo.tsx
  src/widgets/mobile-view/ui/mobile-view.tsx
Labels: preview, testing

#483 439-fix: Correct principle card behavior
  src/widgets/principles/ui/principle-card/principle-card.scss
  src/widgets/principles/ui/principle-card/principle-card.tsx
  src/widgets/principles/ui/principle-card/principles.scss
  src/widgets/principles/ui/principle-card/principles.tsx
Labels: preview

#497 496-feat: Update active trainers
  src/shared/assets/mentors/s-koksharov.webp
  src/widgets/trainers/javascript-ru.data.ts
Labels: preview

#470 457-refactor: Move data files
  dev-data/about.data.ts
  dev-data/angular-path.data.ts
  dev-data/angular.data.ts
  dev-data/aws-dev-path.data.ts
  dev-data/aws-devops.data.ts
  dev-data/awsDev.data.ts
  dev-data/awsFundamentals.data.ts
  dev-data/communication.data.ts
  dev-data/courseTitles.data.ts
  dev-data/courses-data.types.ts
  dev-data/courses-path.data.ts
  dev-data/courses.data.ts
  dev-data/events.data.ts
  dev-data/faq.data.ts
  dev-data/index.ts
  dev-data/javascript-ru.data.ts
  dev-data/js-path.data.ts
  dev-data/js-ru-path.data.ts
  dev-data/nodejs.data.ts
  dev-data/preSchool.data.ts
  dev-data/react-en.data.ts
  dev-data/react-ru.data.ts
  dev-data/required.data.ts
  dev-data/trainers.types.ts
  dev-data/training-program.data.tsx
  src/app/services/api/index.ts
  src/app/services/data/index.ts
  src/pages/angular.tsx
  src/pages/aws-developer.tsx
  src/pages/aws-devops.tsx
  src/pages/aws-fundamentals.tsx
  src/pages/javascript-preschool-ru.tsx
  src/pages/javascript-ru.tsx
  src/pages/nodejs.tsx
  src/pages/react.tsx
  src/shared/__tests__/constants.ts
  src/shared/hooks/use-data-by-name/use-data-by-name.test.ts
  src/shared/hooks/use-data-by-name/use-data-by-name.ts
  src/widgets/about/ui/about.tsx
  src/widgets/certification/ui/certification.tsx
  src/widgets/communication/ui/communication.tsx
  src/widgets/course-main/courseLoader.ts
  src/widgets/courses-school/ui/courses.tsx
  src/widgets/events/ui/events.tsx
  src/widgets/faq/ui/faq.tsx
  src/widgets/required/ui/required.tsx
  src/widgets/study-path/ui/study-path.tsx
  src/widgets/trainers/ui/trainers-card/trainer-card.tsx
  src/widgets/trainers/ui/trainers.tsx
  src/widgets/training-program/ui/training-program.tsx
  tsconfig.json
  vite.config.ts
  vitest.config.ts
Labels: preview

#488 271-refactor: Add width and height to header icons
  src/app/layouts/base-layout/components/header/nav-item/nav-item.module.scss
Labels: refactor, preview

#487 276-refactor: Add links descriptive text in Upcoming courses section
  src/widgets/courses-school/courses.test.tsx
  src/widgets/courses-school/ui/courses.tsx
Labels: refactor, preview

#468 363-feat: Keyboard accessible nav menu
  src/app/layouts/base-layout/components/header/header.test.tsx
  src/app/layouts/base-layout/components/header/nav-item/nav-item.module.scss
  src/app/layouts/base-layout/components/header/nav-item/nav-item.tsx
Labels: preview

#466 465-refactor: Customize slider
  src/widgets/events/ui/events.tsx
  src/widgets/pictures/pictures.test.tsx
  src/widgets/pictures/ui/pictures.scss
  src/widgets/pictures/ui/pictures.tsx
Labels: refactor, preview

#495 493-refactor: Replace font family
  index.html
  src/app/layouts/base-layout/components/header/nav-item/nav-item.module.scss
  src/app/styles/_constants.scss
  src/widgets/hero/ui/hero.scss
Labels: refactor, preview

#475 355-refactor: Paragraph component refactor
  src/shared/__tests__/visualTesting/community.spec.ts-snapshots/community-Mobile-Chrome-darwin.png
  src/shared/__tests__/visualTesting/community.spec.ts-snapshots/community-Mobile-Safari-darwin.png
  src/shared/__tests__/visualTesting/community.spec.ts-snapshots/community-chromium-darwin.png
  src/shared/__tests__/visualTesting/community.spec.ts-snapshots/community-firefox-darwin.png
  src/shared/__tests__/visualTesting/community.spec.ts-snapshots/community-webkit-darwin.png
  src/shared/__tests__/visualTesting/courses.spec.ts-snapshots/courses-Mobile-Chrome-darwin.png
  src/shared/__tests__/visualTesting/courses.spec.ts-snapshots/courses-Mobile-Safari-darwin.png
  src/shared/__tests__/visualTesting/courses.spec.ts-snapshots/courses-chromium-darwin.png
  src/shared/__tests__/visualTesting/courses.spec.ts-snapshots/courses-firefox-darwin.png
  src/shared/__tests__/visualTesting/courses.spec.ts-snapshots/courses-webkit-darwin.png
  src/shared/__tests__/visualTesting/main.spec.ts-snapshots/main-Mobile-Chrome-darwin.png
  src/shared/__tests__/visualTesting/main.spec.ts-snapshots/main-Mobile-Safari-darwin.png
  src/shared/__tests__/visualTesting/main.spec.ts-snapshots/main-chromium-darwin.png
  src/shared/__tests__/visualTesting/main.spec.ts-snapshots/main-firefox-darwin.png
  src/shared/__tests__/visualTesting/main.spec.ts-snapshots/main-webkit-darwin.png
  src/shared/__tests__/visualTesting/report/index.html
  src/shared/ui/paragraph/paragraph.module.scss
  src/shared/ui/paragraph/paragraph.scss
  src/shared/ui/paragraph/paragraph.test.tsx
  src/shared/ui/paragraph/paragraph.tsx
  src/widgets/about-home/ui/about.scss
  src/widgets/about-home/ui/about.tsx
  src/widgets/about-school/ui/about.scss
  src/widgets/about-school/ui/about.tsx
  src/widgets/alumni/ui/alumni.scss
  src/widgets/alumni/ui/alumni.tsx
  src/widgets/communication/ui/communication.scss
  src/widgets/communication/ui/communication.tsx
  src/widgets/community/ui/community.tsx
  src/widgets/contribute/ui/contribute.scss
  src/widgets/contribute/ui/contribute.tsx
  src/widgets/events/ui/events.module.scss
  src/widgets/events/ui/events.tsx
  src/widgets/mentors/ui/mentors.scss
  src/widgets/mentors/ui/mentors.tsx
  src/widgets/merch/ui/merch.module.scss
  src/widgets/merch/ui/merch.tsx
  src/widgets/not-found/ui/not-found.scss
  src/widgets/not-found/ui/not-found.tsx
  src/widgets/numbers/ui/numbers.tsx
  src/widgets/speakers/speakers.test.tsx
  src/widgets/speakers/ui/speakers.scss
  src/widgets/speakers/ui/speakers.tsx
  src/widgets/study-path/ui/study-path.scss
  src/widgets/study-with-us/ui/study-with-us.scss
  src/widgets/study-with-us/ui/study-with-us.tsx
  src/widgets/support/ui/support.tsx
Labels: refactor, preview

#507 502-fix: Links accessibility on mobile
  src/widgets/courses-school/courses.test.tsx
  src/widgets/courses-school/ui/CourseCard.tsx
Labels: bug, preview

#506 500-refactor: Widget angular topics
  src/widgets/angular-topics/constants.ts
  src/widgets/angular-topics/ui/angular-topics.test.tsx
  src/widgets/angular-topics/ui/angular-topics.tsx
Labels: refactor, preview

#492 473-fix: Fsd refactor trainers card
  dev-data/angular.data.ts
  dev-data/aws-devops.data.ts
  dev-data/awsDev.data.ts
  dev-data/awsFundamentals.data.ts
  dev-data/index.ts
  dev-data/javascript-ru.data.ts
  dev-data/nodejs.data.ts
  dev-data/preSchool.data.ts
  dev-data/react-en.data.ts
  dev-data/react-ru.data.ts
  src/entities/trainer/index.ts
  src/entities/trainer/types.ts
  src/entities/trainer/ui/trainers-card/trainer-card.module.scss
  src/entities/trainer/ui/trainers-card/trainer-card.test.tsx
  src/entities/trainer/ui/trainers-card/trainer-card.tsx
  src/shared/__tests__/constants.ts
  src/widgets/trainers/trainers.test.tsx
  src/widgets/trainers/ui/trainers-card/trainer-card.tsx
  src/widgets/trainers/ui/trainers.scss
  src/widgets/trainers/ui/trainers.tsx
Labels: refactor, preview

#512 511-feat: Simplify course titles
  src/pages/javascript-en.tsx
  src/pages/javascript-ru.tsx
  src/widgets/breadcrumbs/constants.ts
  src/widgets/course-main/course-main.tsx
Labels: feature, preview

#401 375-refactor: Subtitle component refactor
  dev-data/training-program.data.tsx
  src/shared/ui/subtitle/subtitle.module.scss
  src/shared/ui/subtitle/subtitle.scss
  src/shared/ui/subtitle/subtitle.test.tsx
  src/shared/ui/subtitle/subtitle.tsx
  src/widgets/certification/ui/certification.module.scss
  src/widgets/communication/ui/communication.scss
  src/widgets/communication/ui/communication.tsx
  src/widgets/community/ui/community.scss
  src/widgets/course-main/course-main.tsx
  src/widgets/hero/ui/hero.scss
  src/widgets/hero/ui/hero.tsx
  src/widgets/main/ui/main.scss
  src/widgets/main/ui/main.tsx
  src/widgets/mentors/ui/mentors.scss
  src/widgets/mentors/ui/mentors.tsx
  src/widgets/merch/ui/merch.tsx
  src/widgets/numbers/ui/numbers.scss
  src/widgets/required/ui/required.scss
  src/widgets/required/ui/required.tsx
  src/widgets/support/ui/support.scss
  src/widgets/support/ui/support.tsx
Labels: refactor, preview

#519 Workflow another fix 3
  .github/workflows/visual-testing.yml
Labels: preview

#467 282-feat: Standardize links designation
  dev-data/about.data.tsx
  dev-data/training-program.data.tsx
  src/app/styles/_constants.scss
  src/entities/courses/ui/course-card/course-card.tsx
  src/entities/events/ui/event-card/event-card.tsx
  src/shared/icons/arrow-icon.tsx
  src/shared/icons/text-link-icon.tsx
  src/shared/ui/link-custom/link-custom.module.scss
  src/shared/ui/link-custom/link-custom.test.tsx
  src/shared/ui/link-custom/link-custom.tsx
  src/shared/ui/social-media/social-media.test.tsx
  src/shared/ui/social-media/social-media.tsx
  src/shared/ui/text-with-link/text-with-link.scss
  src/shared/ui/text-with-link/text-with-link.tsx
  src/widgets/about/ui/about.tsx
  src/widgets/about/ui/info-grid/info-grid.scss
  src/widgets/about/ui/info-grid/info-grid.tsx
  src/widgets/communication/ui/communication.tsx
  src/widgets/course-main/course-main.tsx
  src/widgets/courses-school/courses.test.tsx
  src/widgets/courses-school/ui/CourseCard.tsx
  src/widgets/courses-school/ui/courses.tsx
  src/widgets/mentors-wanted/ui/mentors-wanted.module.scss
  src/widgets/mentors-wanted/ui/mentors-wanted.tsx
  src/widgets/mentors/ui/mentors.tsx
  src/widgets/merch/ui/merch.tsx
  src/widgets/not-found/ui/not-found.tsx
  src/widgets/option-item/ui/option-item.tsx
  src/widgets/pictures/pictures.test.tsx
  src/widgets/requirements/ui/requirements.tsx
  src/widgets/study-path/study-path.test.tsx
  src/widgets/study-path/ui/stage-card/links/links.scss
  src/widgets/study-path/ui/stage-card/links/links.test.tsx
  src/widgets/study-path/ui/stage-card/links/links.tsx
  src/widgets/study-path/ui/stage-card/stage-card.test.tsx
  src/widgets/study-path/ui/stages/stages.test.tsx
  src/widgets/support/ui/support.tsx
  src/widgets/training-program/ui/training-program.scss
  src/widgets/training-program/ui/training-program.tsx
Labels: preview

#494 472-refactor: Entities event refactor
  dev-data/events.data.ts
  src/app/styles/_constants.scss
  src/app/styles/_mixins.scss
  src/entities/event/index.ts
  src/entities/event/types.ts
  src/entities/event/ui/event-card/event-card.module.scss
  src/entities/event/ui/event-card/event-card.test.tsx
  src/entities/event/ui/event-card/event-card.tsx
  src/entities/events/index.ts
  src/entities/events/ui/event-card/event-card.test.tsx
  src/shared/helpers/getActualData.test.ts
  src/shared/helpers/getActualData.ts
  src/widgets/events/ui/events.tsx
Labels: refactor, preview

#528 527-fix: Position arrows in slider
  src/widgets/pictures/ui/pictures.scss
Labels: preview

#526 525-fix: Event card link icon styles
  src/widgets/events/ui/events.module.scss
  src/widgets/events/ui/events.tsx
Labels: bug, high priority, preview

#516 504-refactor: Fsd widget breadcrumbs
  src/widgets/breadcrumbs/constants.ts
  src/widgets/breadcrumbs/index.ts
  src/widgets/breadcrumbs/types.ts
  src/widgets/breadcrumbs/ui/breadcrumb-item.test.tsx
  src/widgets/breadcrumbs/ui/breadcrumb-item.tsx
  src/widgets/breadcrumbs/ui/breadcrumbs.module.scss
  src/widgets/breadcrumbs/ui/breadcrumbs.scss
  src/widgets/breadcrumbs/ui/breadcrumbs.test.tsx
  src/widgets/breadcrumbs/ui/breadcrumbs.tsx
Labels: refactor, preview

#503 471-refactor: Entity course
  dev-data/courses-data.types.ts
  dev-data/courses.data.ts
  src/app/styles/_constants.scss
  src/app/types/course-status.types.ts
  src/app/types/index.ts
  src/entities/course/index.ts
  src/entities/course/types.ts
  src/entities/course/ui/course-card/course-card.module.scss
  src/entities/course/ui/course-card/course-card.test.tsx
  src/entities/course/ui/course-card/course-card.tsx
  src/entities/courses/index.ts
  src/entities/courses/types.ts
  src/entities/courses/ui/course-card/course-card.scss
  src/entities/courses/ui/course-card/course-card.test.tsx
  src/entities/event/ui/event-card/event-card.module.scss
  src/pages/courses.tsx
  src/shared/helpers/getActualData.test.ts
  src/shared/helpers/getActualData.ts
  src/shared/helpers/is-course.ts
  src/shared/hooks/use-course-by-title/use-course-by-title.ts
  src/shared/hooks/use-course-by-title/utils/is-course.ts
  src/shared/hooks/use-course-by-title/utils/select-course.ts
  src/widgets/about/ui/about.tsx
  src/widgets/course-main/course-main.test.tsx
  src/widgets/course-main/course-main.tsx
  src/widgets/course-main/utils/get-course-status.ts
  src/widgets/courses-school/ui/CourseCard.tsx
  src/widgets/courses-school/ui/courses.tsx
  src/widgets/courses/ui/courses.scss
  src/widgets/courses/ui/courses.tsx
  src/widgets/general/general.scss
  src/widgets/general/general.test.tsx
  src/widgets/general/general.tsx
  src/widgets/general/index.ts
  src/widgets/main/index.ts
  src/widgets/main/ui/main/main.scss
  src/widgets/main/ui/main/main.test.tsx
  src/widgets/main/ui/main/main.tsx
  src/widgets/school-menu/ui/school-item/school-item.tsx
  src/widgets/school-menu/ui/school-list/school-list.tsx
  src/widgets/school-menu/ui/school-menu.tsx
  src/widgets/training-program/ui/training-program.tsx
Labels: refactor, preview

#509 491-refactor: Widget about school
  src/app/const/index.ts
  src/app/layouts/base-layout/components/footer/about-list.tsx
  src/pages/home.tsx
  src/shared/ui/link-custom/link-custom.test.tsx
  src/widgets/about-school/index.ts
  src/widgets/about-school/ui/about-school.test.tsx
  src/widgets/about-school/ui/about-school.tsx
  src/widgets/about-school/ui/about.scss
  src/widgets/about-school/ui/about.tsx
  src/widgets/school-menu/ui/school-menu.tsx
Labels: refactor, preview

#510 490-refactor: Widget about home
  src/app/const/index.ts
  src/pages/community.tsx
  src/widgets/about-community/index.ts
  src/widgets/about-community/ui/about-community.module.scss
  src/widgets/about-community/ui/about-community.test.tsx
  src/widgets/about-community/ui/about-community.tsx
  src/widgets/about-home/about.test.tsx
  src/widgets/about-home/index.ts
  src/widgets/about-home/ui/about.scss
  src/widgets/school-menu/ui/school-menu.tsx
Labels: refactor, preview

#538 498-refactor: Widget about video
  dev-data/about-video.data.ts
  dev-data/index.ts
  src/shared/constants.ts
  src/widgets/about-video/about-video.test.tsx
  src/widgets/about-video/ui/about-video.module.scss
  src/widgets/about-video/ui/about-video.scss
  src/widgets/about-video/ui/about-video.test.tsx
  src/widgets/about-video/ui/about-video.tsx
Labels: refactor, preview

#536 521-refactor: Fsd widget communication
  dev-data/index.ts
  dev-data/widget-communication.data.ts
  src/widgets/communication/communication.test.tsx
  src/widgets/communication/ui/communication.module.scss
  src/widgets/communication/ui/communication.scss
  src/widgets/communication/ui/communication.test.tsx
  src/widgets/communication/ui/communication.tsx
Labels: refactor, preview

#540 513-refactor: Widget hero
  dev-data/hero-page.data.ts
  dev-data/index.ts
  src/pages/community.tsx
  src/pages/courses.tsx
  src/pages/home.tsx
  src/shared/constants.ts
  src/widgets/hero-page/index.ts
  src/widgets/hero-page/types.ts
  src/widgets/hero-page/ui/hero-page.module.scss
  src/widgets/hero-page/ui/hero-page.test.tsx
  src/widgets/hero-page/ui/hero-page.tsx
  src/widgets/hero/hero.test.tsx
  src/widgets/hero/index.ts
  src/widgets/hero/ui/hero.scss
  src/widgets/hero/ui/hero.tsx
  src/widgets/main/index.ts
  src/widgets/main/main.test.tsx
  src/widgets/main/ui/main.scss
  src/widgets/main/ui/main.tsx
  src/widgets/main/ui/main/main.scss
  src/widgets/main/ui/main/main.test.tsx
  src/widgets/main/ui/main/main.tsx
Labels: refactor, preview

#501 499-refactor: Widget alumni
  src/widgets/alumni/alumni.test.tsx
  src/widgets/alumni/constants.ts
  src/widgets/alumni/ui/alumni.module.scss
  src/widgets/alumni/ui/alumni.scss
  src/widgets/alumni/ui/alumni.test.tsx
  src/widgets/alumni/ui/alumni.tsx
Labels: refactor, preview

#545 533-refactor: Widget courses
  src/widgets/courses/constants.ts
  src/widgets/courses/other-courses.test.tsx
  src/widgets/courses/ui/courses.module.scss
  src/widgets/courses/ui/courses.scss
  src/widgets/courses/ui/courses.test.tsx
  src/widgets/courses/ui/courses.tsx
Labels: refactor, preview

#547 546-refactor: Widget StudyWithUs
  src/widgets/contribute/ui/contribute.tsx
  src/widgets/option-item/index.ts
  src/widgets/option-item/option-item.test.tsx
  src/widgets/option-item/ui/option-item.module.scss
  src/widgets/option-item/ui/option-item.scss
  src/widgets/option-item/ui/option-item.test.tsx
  src/widgets/option-item/ui/option-item.tsx
  src/widgets/study-with-us/constants.ts
  src/widgets/study-with-us/study-with-us.test.tsx
  src/widgets/study-with-us/ui/study-with-us.module.scss
  src/widgets/study-with-us/ui/study-with-us.scss
  src/widgets/study-with-us/ui/study-with-us.test.tsx
  src/widgets/study-with-us/ui/study-with-us.tsx
Labels: refactor, preview

#570 378-fix: Add trainers to en course
  dev-data/index.ts
  dev-data/javascript-en.data.ts
  src/pages/javascript-en.tsx
  src/shared/assets/mentors/a-milashevich.webp
Labels: bug, preview

#571 524-fix: Option item bug
  src/widgets/contribute/ui/contribute.scss
Labels: bug, preview
