Repository rolling-scopes/site, pull requests merged in 2024-06, with the labels that each got.

#246 242-feat: data certification block
  src/features/certification/certification.module.scss
  src/features/certification/certification.tsx
  src/pages/angular.tsx
  src/pages/aws-developer.tsx
  src/pages/aws-fundamentals.tsx
  src/pages/javascript-en.tsx
  src/pages/javascript-preschool-ru.tsx
  src/pages/javascript-ru.tsx
  src/pages/nodejs.tsx
  src/pages/react.tsx
Labels: preview

#249 234-fix: Missing favicon display
  index.html
  public/favicon.ico
  public/favicon.png
  public/favicon.svg
Labels: bug, preview

#236 49-feat: Auto remove old events
  src/app/services/dayjs/index.ts
  src/features/home/events/events.data.ts
  src/features/home/events/events.module.scss
  src/features/home/events/events.tsx
  src/utils/getActualDataList.ts
  src/utils/index.ts
Labels: feature, refactor, preview

#261 260-feat: update aws cloud trainers
  src/assets/mentors/ac-akbarov.webp
  src/assets/mentors/ac-danilov.webp
  src/assets/mentors/ac-konyakhin.webp
  src/assets/mentors/ac-kustikov.webp
  src/features/trainers/awsDev.data.ts
Labels: preview

#291 290-doc: Edit sample of the bug report
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: documentation

#289 280-fix: Fix dates in mock events
  src/features/home/events/events.data.ts
  src/features/home/events/events.test.tsx
  src/features/home/events/events.tsx
Labels: bug, high priority, preview

#302 248-fix: Update block 'Certificate' in 'About the course' section on Courses pages
  src/features/about/about.data.ts
Labels: bug, preview

#297 265-fix: Page navigation issue
  src/__tests__/visualTesting/community.spec.ts-snapshots/community-Mobile-Chrome-darwin.png
  src/__tests__/visualTesting/community.spec.ts-snapshots/community-Mobile-Safari-darwin.png
  src/__tests__/visualTesting/community.spec.ts-snapshots/community-chromium-darwin.png
  src/__tests__/visualTesting/community.spec.ts-snapshots/community-firefox-darwin.png
  src/__tests__/visualTesting/community.spec.ts-snapshots/community-webkit-darwin.png
  src/__tests__/visualTesting/courses.spec.ts-snapshots/courses-Mobile-Chrome-darwin.png
  src/__tests__/visualTesting/courses.spec.ts-snapshots/courses-Mobile-Safari-darwin.png
  src/__tests__/visualTesting/courses.spec.ts-snapshots/courses-chromium-darwin.png
  src/__tests__/visualTesting/courses.spec.ts-snapshots/courses-firefox-darwin.png
  src/__tests__/visualTesting/courses.spec.ts-snapshots/courses-webkit-darwin.png
  src/__tests__/visualTesting/main.spec.ts-snapshots/main-Mobile-Chrome-darwin.png
  src/__tests__/visualTesting/main.spec.ts-snapshots/main-Mobile-Safari-darwin.png
  src/__tests__/visualTesting/main.spec.ts-snapshots/main-chromium-darwin.png
  src/__tests__/visualTesting/main.spec.ts-snapshots/main-firefox-darwin.png
  src/__tests__/visualTesting/main.spec.ts-snapshots/main-webkit-darwin.png
  src/features/home/merch/merch.scss
  src/features/school/about/about.scss
  src/features/school/courses/courses.scss
  src/features/school/mentors/mentors.scss
  src/styles/index.scss
Labels: high priority, preview

#304 292-feat: Increase logo for mobile
  src/assets/svg/rss-logo.svg
Labels: preview

#303 263-fix: Remove buttons block on the Community page hero
  src/features/home/hero/hero.scss
  src/features/home/hero/hero.test.tsx
  src/features/home/hero/hero.tsx
  src/features/home/hero/tag-divider/index.ts
  src/features/home/hero/tag-divider/tag-divider.scss
  src/features/home/hero/tag-divider/tag-divider.test.tsx
  src/features/home/hero/tag-divider/tag-divider.tsx
Labels: bug, preview

#251 225-feat: update angular info
  src/assets/mentors-wanted-poster.webp
  src/features/angular-topics/angular-topics.module.scss
  src/features/angular-topics/angular-topics.tsx
  src/features/angular-topics/index.ts
  src/features/mentors-wanted/index.ts
  src/features/mentors-wanted/mentors-wanted.module.scss
  src/features/mentors-wanted/mentors-wanted.tsx
  src/features/required/required.data.ts
  src/features/required/required.test.tsx
  src/features/training-program/training-program.data.tsx
  src/features/training-program/training-program.scss
  src/features/training-program/training-program.test.tsx
  src/pages/angular.tsx
Labels: preview

#307 293-fix: Mobile menu layout bugs
  src/app/components/mobile-view/mobile-view.scss
  src/features/base-layout/components/header/burger/burger.module.scss
Labels: preview

#310 288-fix: React code ESLint issues
  eslint.config.js
  src/features/home/merch/merch.tsx
  src/features/image/image.tsx
  src/features/not-found/not-found.tsx
  src/features/required/required.tsx
  src/features/school/requirements/requirements.tsx
  src/features/training-program/training-program.data.tsx
  src/features/training-program/training-program.tsx
Labels: bug, high priority, preview

#324 202-fix: Loading indicator bug
  src/app/app.tsx
  src/app/styles/index.scss
Labels: preview

#332 283-fix: fix 'https://rollingscopes.com/' redirect
  .github/workflows/production.yml
  src/app/app.tsx
  src/app/layouts/base-layout/components/footer/about-list.tsx
  src/app/layouts/base-layout/components/header/header.tsx
  src/app/routes.tsx
  src/app/services/data/courses-path.data.ts
  src/app/services/data/courses.data.ts
  src/app/services/platform/index.ts
  src/config.ts
  src/pages/community.tsx
  src/pages/home.tsx
  src/pages/school.tsx
  src/shared/ui/breadcrumbs/breadcrumbs.scss
  src/shared/ui/breadcrumbs/breadcrumbs.test.tsx
  src/shared/ui/breadcrumbs/breadcrumbs.tsx
  src/shared/ui/breadcrumbs/breadcrumbs.types.ts
  src/shared/ui/breadcrumbs/constants.ts
  src/widgets/breadcrumbs/breadcrumbs.test.tsx
  src/widgets/breadcrumbs/index.ts
  src/widgets/breadcrumbs/ui/breadcrumbs.scss
  src/widgets/breadcrumbs/ui/breadcrumbs.tsx
  src/widgets/courses-school/courses.test.tsx
  src/widgets/mobile-view/ui/mobile-view.tsx
Labels: bug, high priority, preview

#337 355-feat: configure qodana github actions
  .github/workflows/code-quality.yml
Labels: feature

#341 299-fix: focus on course card differs
  src/entities/courses/ui/course-card/course-card.scss
Labels: preview

#340 330-fix: no gap in merch section
  src/widgets/merch/ui/merch.module.scss
  src/widgets/merch/ui/merch.scss
  src/widgets/merch/ui/merch.tsx
Labels: preview

#344 343-fix: course description bug
  src/widgets/training-program/training-program.data.tsx
Labels: preview

#349 58-feat: Add new trainer to javascript-preschool-ru
  src/shared/assets/mentors/Vitalii-Rogozin.png
  src/widgets/trainers/preSchool.data.ts
Labels: preview

#353 352-fix: qodana eslint error
  .github/workflows/code-quality.yml
  .github/workflows/main.yml
Labels: bug, high priority
