Repository rolling-scopes/site, pull requests merged in 2024-05, with the labels that each got.

#170 Fix: layout distortion on zoom out
  src/features/base-layout/components/navbar/navbar.scss
  src/features/base-layout/components/navbar/navbar.tsx
  src/features/home/numbers/numbers.scss
  src/styles/index.scss
Labels: bug

#139 Fix: fix course labels
  package-lock.json
  package.json
  src/app/components/date-lang/date-lang.module.scss
  src/app/components/date-lang/date-lang.scss
  src/app/components/date-lang/date-lang.tsx
  src/app/components/subtitle/subtitle.scss
  src/app/components/subtitle/subtitle.tsx
  src/app/services/dayjs/index.ts
  src/app/types/course-status.types.ts
  src/app/types/index.ts
  src/features/course-main/course-main.module.scss
  src/features/course-main/course-main.scss
  src/features/course-main/course-main.test.tsx
  src/features/course-main/course-main.tsx
  src/features/course-main/utils/get-course-status.ts
  src/features/course-main/utils/index.ts
  src/features/сourse-main/utils/has-day.ts
  src/main.tsx
Labels: bug, high priority

#168 refactor/change router to use lazy routes
  package-lock.json
  package.json
  src/app/app.tsx
  src/app/hooks/use-course-by-title/use-course-by-title.ts
  src/app/hooks/use-course-by-title/utils/is-course.ts
  src/app/hooks/use-course-by-title/utils/select-course.ts
  src/app/routes.tsx
  src/features/base-layout/base-layout.tsx
  src/features/course-main/course-main.test.tsx
  src/features/course-main/course-main.tsx
  src/features/course-main/courseLoader.ts
Labels: refactor

#182 Refactor: change precommit to not run *:fix
  lint-staged.config.mjs
  package-lock.json
  package.json
Labels: refactor, high priority

#185 Docs: document image optimization
  readme/image-optimization/assets/bad-performance.png
  readme/image-optimization/assets/watch-close.png
  readme/image-optimization/image-optimization.md
Labels: documentation, high priority

#188 Refactor: move all routes to constant
  src/__tests__/utils/render-with-router/render-with-router.tsx
  src/app/components/breadcrumbs/breadcrumbs.test.tsx
  src/app/components/breadcrumbs/breadcrumbs.tsx
  src/app/components/breadcrumbs/breadcrumbs.types.ts
  src/app/components/breadcrumbs/constants.ts
  src/app/const/index.ts
  src/app/hooks/use-data-by-name/use-data-by-name.test.ts
  src/app/routes.tsx
  src/app/services/data/courses-path.data.ts
  src/app/services/data/courses.data.ts
  src/app/services/platform/index.ts
  src/app/types/route.types.ts
  src/features/base-layout/components/scroll-to-hash/scroll-to-hash.test.tsx
  src/features/home/courses/courses.tsx
  src/features/training-program/training-program.test.tsx
Labels: refactor, high priority

#189 Test: visual testing integration
  .gitignore
  package-lock.json
  package.json
  playwright.config.ts
  readme/assets/UI.jpg
  readme/assets/origin-diff.png
  readme/end-to-end-testing.md
  src/__tests__/visualTesting/footer.spec.ts
  src/__tests__/visualTesting/footer.spec.ts-snapshots/footer-Mobile-Chrome-win32.png
  src/__tests__/visualTesting/footer.spec.ts-snapshots/footer-Mobile-Safari-win32.png
  src/__tests__/visualTesting/footer.spec.ts-snapshots/footer-chromium-win32.png
  src/__tests__/visualTesting/footer.spec.ts-snapshots/footer-firefox-win32.png
  src/__tests__/visualTesting/footer.spec.ts-snapshots/footer-webkit-win32.png
  src/__tests__/visualTesting/fullpage.spec.ts
  src/__tests__/visualTesting/fullpage.spec.ts-snapshots/origin-fullpage-Mobile-Chrome-win32.png
  src/__tests__/visualTesting/fullpage.spec.ts-snapshots/origin-fullpage-Mobile-Safari-win32.png
  src/__tests__/visualTesting/fullpage.spec.ts-snapshots/origin-fullpage-chromium-win32.png
  src/__tests__/visualTesting/fullpage.spec.ts-snapshots/origin-fullpage-firefox-win32.png
  src/__tests__/visualTesting/fullpage.spec.ts-snapshots/origin-fullpage-webkit-win32.png
  src/__tests__/visualTesting/navbar.spec.ts
  src/__tests__/visualTesting/navbar.spec.ts-snapshots/navbar-Mobile-Chrome-win32.png
  src/__tests__/visualTesting/navbar.spec.ts-snapshots/navbar-Mobile-Safari-win32.png
  src/__tests__/visualTesting/navbar.spec.ts-snapshots/navbar-chromium-win32.png
  src/__tests__/visualTesting/navbar.spec.ts-snapshots/navbar-firefox-win32.png
  src/__tests__/visualTesting/navbar.spec.ts-snapshots/navbar-webkit-win32.png
  tsconfig.json
  vitest.config.ts
Labels: documentation, feature

#205 Docs: style guide - colors & opacity
  readme/assets/styleguide-design/color-primary-black.svg
  readme/assets/styleguide-design/color-primary-white.svg
  readme/assets/styleguide-design/color-purple-400.svg
  readme/assets/styleguide-design/color-purple-50.svg
  readme/assets/styleguide-design/color-secondary-gray-100.svg
  readme/assets/styleguide-design/color-secondary-gray-200.svg
  readme/assets/styleguide-design/color-secondary-gray-400.svg
  readme/assets/styleguide-design/color-secondary-gray-500.svg
  readme/assets/styleguide-design/color-secondary-gray-600.svg
  readme/assets/styleguide-design/color-secondary-red.svg
  readme/assets/styleguide-design/color-secondary-yellow-100.svg
  readme/assets/styleguide-design/color-secondary-yellow-50.svg
  readme/assets/styleguide-design/color-secondary-yellow-500.svg
  readme/assets/styleguide-design/color-secondary-yellow-700.svg
  readme/assets/styleguide-design/color-secondary-yellow.svg
  readme/assets/styleguide-design/token-naming-color.png
  readme/assets/styleguide-design/token-naming-opacity.png
  readme/styleguide-design.md
  src/app/components/actions/actions.scss
  src/app/components/breadcrumbs/breadcrumbs.scss
  src/app/components/button-outlined/button-outlined.scss
  src/app/components/button/button.scss
  src/app/components/course-card/course-card.scss
  src/app/components/date-lang/date-lang.module.scss
  src/app/components/event-card/event-card.scss
  src/app/components/mobile-view/mobile-view.scss
  src/app/components/option-item/option-item.scss
  src/app/components/paragraph/paragraph.scss
  src/app/components/places/places.scss
  src/app/components/principle-card/principle-card.scss
  src/app/components/school-menu/school-menu.scss
  src/app/components/section-label/section-label.scss
  src/app/components/social-media/social-media.scss
  src/app/components/subtitle/subtitle.scss
  src/app/components/title/title.scss
  src/features/about/components/info-grid/info-grid.scss
  src/features/base-layout/components/footer/footer.scss
  src/features/base-layout/components/navbar/navbar.scss
  src/features/base-layout/components/partnered/partnered.scss
  src/features/course-main/course-main.module.scss
  src/features/courses/general/general.scss
  src/features/courses/main/main.scss
  src/features/courses/mentoring/mentoring.scss
  src/features/courses/mentors/mentors.scss
  src/features/courses/requirements/requirements.scss
  src/features/home/contribute/contribute.scss
  src/features/home/courses/courses.scss
  src/features/home/hero/components/tag-divider/tag-divider.scss
  src/features/home/hero/components/tag/tag.scss
  src/features/home/hero/hero.scss
  src/features/home/numbers/numbers.scss
  src/features/home/speakers/speakers.scss
  src/features/home/support/support.scss
  src/features/study-path/components/stage-card/links/links.scss
  src/features/study-path/components/stage-card/stage-card.scss
  src/features/study-path/components/stage-card/step/step.scss
  src/features/trainers/trainers.scss
  src/styles/_constants.scss
  src/styles/index.scss
Labels: documentation

#217 Feature: dividing JavaScript courses into separate ru and en pages.
  src/app/components/breadcrumbs/constants.ts
  src/app/const/index.ts
  src/app/hooks/use-course-by-title/use-course-by-title.test.tsx
  src/app/hooks/use-course-by-title/use-course-by-title.ts
  src/app/hooks/use-course-by-title/utils/select-course.ts
  src/app/hooks/use-data-by-name/use-data-by-name.test.ts
  src/app/routes.tsx
  src/app/services/api/index.ts
  src/app/services/data/courses-data.types.ts
  src/app/services/data/courses-path.data.ts
  src/app/services/data/courses.data.ts
  src/app/services/data/index.ts
  src/app/services/data/js-ru-path.data.ts
  src/app/types/course.types.ts
  src/app/types/index.ts
  src/data/communication.data.ts
  src/features/about-video/about-video.tsx
  src/features/about/about.data.ts
  src/features/about/about.scss
  src/features/about/about.tsx
  src/features/communication/communication.test.tsx
  src/features/course-main/course-main.test.tsx
  src/features/course-main/course-main.tsx
  src/features/home/courses/courses.tsx
  src/features/required/required.data.ts
  src/features/required/required.tsx
  src/features/required/required.types.ts
  src/features/study-path/components/stage-card/topics/topics.tsx
  src/features/study-path/study-path.tsx
  src/features/training-program/training-program.data.tsx
  src/features/training-program/training-program.test.tsx
  src/features/training-program/training-program.tsx
  src/pages/javascript-en.tsx
  src/pages/javascript-preschool-ru.tsx
  src/pages/javascript-ru.tsx
Labels: refactor, high priority

#218 Documentation: replace the template readme file with additional information
  README.md
Labels: documentation

#220 Fix stylelint space indents, empty spaces
  .stylelintrc.json
  package-lock.json
  package.json
  src/app/components/button-outlined/button-outlined.scss
  src/app/components/externalLink/external-link.scss
  src/app/components/logo-wrapper/logo-wrapper.scss
  src/app/components/social-media/social-media.scss
  src/app/components/text-with-link/text-with-link.scss
  src/app/components/title/title.scss
  src/features/base-layout/components/navbar/navbar.scss
  src/features/communication/communication.scss
  src/features/course-main/course-main.module.scss
  src/features/courses/courses/courses.scss
  src/features/home/courses/courses.scss
  src/features/home/pictures/pictures.scss
  src/features/home/school/school.scss
  src/features/home/speakers/speakers.scss
  src/styles/_constants.scss
Labels: bug

#221 Feature: adding a translation for a js/ru page
  src/app/services/data/courses.data.ts
  src/app/services/data/js-ru-path.data.ts
  src/features/about/about.data.ts
  src/features/communication/communication.tsx
  src/features/course-main/course-main.tsx
  src/features/required/required.data.ts
  src/features/training-program/training-program.data.tsx
  src/features/training-program/training-program.tsx
  src/pages/javascript-en.tsx
  src/pages/javascript-preschool-ru.tsx
  src/pages/javascript-ru.tsx
Labels: bug, high priority

#209 Refactor Event Card
  src/app/components/event-card/event-card.module.scss
  src/app/components/event-card/event-card.scss
  src/app/components/event-card/event-card.test.tsx
  src/app/components/event-card/event-card.tsx
  src/features/home/events/events.scss
  src/features/trainers/awsDev.data.ts
  src/styles/_mixins.scss
Labels: refactor

#216 Feature: rework header navigation
  src/app/components/breadcrumbs/constants.ts
  src/app/components/logo-wrapper/logo-wrapper.tsx
  src/app/components/mobile-view/mobile-view.tsx
  src/app/routes.tsx
  src/app/types/route.types.ts
  src/features/base-layout/base-layout.test.tsx
  src/features/base-layout/base-layout.tsx
  src/features/base-layout/components/header/burger/burger.module.scss
  src/features/base-layout/components/header/burger/burger.tsx
  src/features/base-layout/components/header/dropdown/dropdown.module.scss
  src/features/base-layout/components/header/dropdown/dropdown.tsx
  src/features/base-layout/components/header/header.module.scss
  src/features/base-layout/components/header/header.test.tsx
  src/features/base-layout/components/header/header.tsx
  src/features/base-layout/components/header/index.ts
  src/features/base-layout/components/header/nav-item/nav-item.module.scss
  src/features/base-layout/components/header/nav-item/nav-item.tsx
  src/features/base-layout/components/index.ts
  src/features/base-layout/components/navbar/burger.tsx
  src/features/base-layout/components/navbar/index.ts
  src/features/base-layout/components/navbar/navbar.scss
  src/features/courses/courses/courses.tsx
  src/features/courses/general/general.scss
  src/features/courses/index.ts
  src/features/courses/main/main.test.tsx
  src/features/courses/main/main.tsx
  src/features/school/about/about.scss
  src/features/school/about/about.tsx
  src/features/school/about/index.ts
  src/features/school/index.ts
  src/features/school/main/index.ts
  src/features/school/main/main.scss
  src/features/school/main/main.test.tsx
  src/features/school/main/main.tsx
  src/features/school/mentoring/index.ts
  src/features/school/mentoring/mentoring.scss
  src/features/school/mentoring/mentoring.test.tsx
  src/features/school/mentoring/mentoring.tsx
  src/features/school/mentors/index.ts
  src/features/school/mentors/mentors.scss
  src/features/school/mentors/mentors.test.tsx
  src/features/school/mentors/mentors.tsx
  src/features/school/requirements/index.ts
  src/features/school/requirements/requirements.scss
  src/features/school/requirements/requirements.test.tsx
  src/features/school/requirements/requirements.tsx
  src/icons/logo.tsx
  src/pages/courses.tsx
  src/pages/home.tsx
  src/pages/school.tsx
Labels: feature, high priority

#238 feat: add preview deploy
  .github/workflows/preview-create.yml
  .github/workflows/preview-delete.yml
  .github/workflows/preview-status.yml
  .github/workflows/production.yml
Labels: preview

#233 223-test: Update screenshots, improve tests
  package-lock.json
  package.json
  playwright.config.ts
  readme/assets/end-to-end-testing/UI.jpg
  readme/assets/end-to-end-testing/origin-diff.png
  readme/end-to-end-testing.md
  src/__tests__/visualTesting/community.spec.ts
  src/__tests__/visualTesting/community.spec.ts-snapshots/community-Mobile-Chrome-win32.png
  src/__tests__/visualTesting/community.spec.ts-snapshots/community-Mobile-Safari-win32.png
  src/__tests__/visualTesting/community.spec.ts-snapshots/community-chromium-win32.png
  src/__tests__/visualTesting/community.spec.ts-snapshots/community-firefox-win32.png
  src/__tests__/visualTesting/community.spec.ts-snapshots/community-webkit-win32.png
  src/__tests__/visualTesting/courses.spec.ts
  src/__tests__/visualTesting/courses.spec.ts-snapshots/courses-Mobile-Chrome-win32.png
  src/__tests__/visualTesting/courses.spec.ts-snapshots/courses-Mobile-Safari-win32.png
  src/__tests__/visualTesting/courses.spec.ts-snapshots/courses-chromium-win32.png
  src/__tests__/visualTesting/courses.spec.ts-snapshots/courses-firefox-win32.png
  src/__tests__/visualTesting/courses.spec.ts-snapshots/courses-webkit-win32.png
  src/__tests__/visualTesting/footer.spec.ts
  src/__tests__/visualTesting/footer.spec.ts-snapshots/footer-Mobile-Chrome-win32.png
  src/__tests__/visualTesting/footer.spec.ts-snapshots/footer-Mobile-Safari-win32.png
  src/__tests__/visualTesting/footer.spec.ts-snapshots/footer-chromium-win32.png
  src/__tests__/visualTesting/footer.spec.ts-snapshots/footer-firefox-win32.png
  src/__tests__/visualTesting/footer.spec.ts-snapshots/footer-webkit-win32.png
  src/__tests__/visualTesting/fullpage.spec.ts
  src/__tests__/visualTesting/fullpage.spec.ts-snapshots/origin-fullpage-Mobile-Chrome-win32.png
  src/__tests__/visualTesting/fullpage.spec.ts-snapshots/origin-fullpage-Mobile-Safari-win32.png
  src/__tests__/visualTesting/fullpage.spec.ts-snapshots/origin-fullpage-chromium-win32.png
  src/__tests__/visualTesting/fullpage.spec.ts-snapshots/origin-fullpage-firefox-win32.png
  src/__tests__/visualTesting/fullpage.spec.ts-snapshots/origin-fullpage-webkit-win32.png
  src/__tests__/visualTesting/main.spec.ts
  src/__tests__/visualTesting/main.spec.ts-snapshots/main-Mobile-Chrome-win32.png
  src/__tests__/visualTesting/main.spec.ts-snapshots/main-Mobile-Safari-win32.png
  src/__tests__/visualTesting/main.spec.ts-snapshots/main-chromium-win32.png
  src/__tests__/visualTesting/main.spec.ts-snapshots/main-firefox-win32.png
  src/__tests__/visualTesting/main.spec.ts-snapshots/main-webkit-win32.png
  src/__tests__/visualTesting/navbar.spec.ts
  src/__tests__/visualTesting/navbar.spec.ts-snapshots/navbar-Mobile-Chrome-win32.png
  src/__tests__/visualTesting/navbar.spec.ts-snapshots/navbar-Mobile-Safari-win32.png
  src/__tests__/visualTesting/navbar.spec.ts-snapshots/navbar-chromium-win32.png
  src/__tests__/visualTesting/navbar.spec.ts-snapshots/navbar-firefox-win32.png
  src/__tests__/visualTesting/navbar.spec.ts-snapshots/navbar-webkit-win32.png
  src/app/components/places/places.tsx
  src/features/base-layout/components/footer/footer.tsx
  src/features/courses/courses/courses.tsx
  src/features/home/events/events.tsx
  src/features/image/image.tsx
  src/features/school/courses/courses.tsx
  tsconfig.json
Labels: documentation, feature, refactor
