Repository rolling-scopes/site, pull requests merged in 2024-04, with the labels that each got.

#59 Add semantiс tags into Alumni component
  src/app/components/paragraph/paragraph.tsx
  src/features/home/alumni/alumni.tsx
Labels: refactor, low priority

#71 Add eslint plugins & configs for code style check & imports sorting
  .eslintrc.cjs
  .prettierrc
  package-lock.json
  package.json
Labels: bug

#84 Fix/trainers component tests
  src/__tests__/constants.ts
  src/features/trainers/trainers.test.tsx
  src/features/trainers/trainers.tsx
  src/pages/angular.tsx
  src/pages/aws-developer.tsx
  src/pages/aws-fundamentals.tsx
  src/pages/nodejs.tsx
  src/pages/react.tsx
Labels: bug, refactor, high priority

#76 Feature/gh actions pr workflow
  .github/CODEOWNERS
  .github/workflows/main.yml
Labels: feature

#37 Fix: fix school menu
  src/app/components/school-menu/school-item.tsx
  src/app/components/school-menu/school-list.tsx
  src/app/components/school-menu/school-menu.scss
  src/app/components/school-menu/school-menu.test.tsx
  src/app/components/school-menu/school-menu.tsx
  src/app/services/data/courses.data.ts
  src/features/base-layout/components/navbar/nav-item.tsx
  src/features/base-layout/components/navbar/navbar.scss
  src/features/base-layout/components/navbar/navbar.test.tsx
  src/icons/dropdown-arrow.tsx
Labels: bug, refactor

#50 Fix: other courses
  package.json
  src/app/hooks/use-nearest-course/constants.ts
  src/app/hooks/use-nearest-course/index.ts
  src/app/hooks/use-nearest-course/types.ts
  src/app/hooks/use-nearest-course/use-nearest-course.ts
  src/app/hooks/use-nearest-course/utils/choose-nearest-course.ts
  src/app/hooks/use-nearest-course/utils/define-prev-next.ts
  src/app/hooks/use-nearest-course/utils/fined-nearest-course.ts
  src/app/services/data/courses.data.ts
  src/features/course-main/course-main.test.tsx
  src/features/course-main/course-main.tsx
  src/features/course-main/utils/has-day.ts
  src/features/courses/courses/courses.scss
  src/features/courses/courses/courses.tsx
  src/features/courses/courses/nearest-courses.test.tsx
  src/features/courses/courses/utils/compare-courses.ts
  src/features/courses/courses/utils/is-course.ts
  src/features/сourse-main/utils/has-day.ts
  src/pages/angular.tsx
Labels: bug, refactor

#89 Feature/configure husky
  .husky/pre-commit
  .husky/pre-push
  package-lock.json
  package.json
Labels: feature, high priority

#100 Refactor/update dependencies & CODEOWNERS
  .github/CODEOWNERS
  package-lock.json
  package.json
Labels: refactor, high priority

#108 Refactor/Update React course description
  src/features/training-program/training-program.data.tsx
Labels: refactor, high priority

#104 feature/configure dependabot
  .github/dependabot.yml
Labels: feature, high priority

#112 feature/setup readme folder
  readme/git-pullrequest-workflow.md
  readme/onboarding.md
  readme/semantic-webaccessibility.md
  readme/styleguide-design.md
  readme/tests.md
Labels: documentation, high priority

#117 Fix SCSS-modules import issue
  .eslintrc.cjs
Labels: bug

#128 Feature/optimize website images
  .eslintrc.cjs
  optimizeImages/lib/const/index.js
  optimizeImages/lib/utils/index.js
  optimizeImages/lib/utils/isSvg.js
  optimizeImages/lib/utils/logCompressed.js
  optimizeImages/lib/utils/logConverted.js
  optimizeImages/lib/utils/logError.js
  optimizeImages/lib/utils/logVariant.js
  optimizeImages/lib/utils/notImage.js
  optimizeImages/lib/utils/paintImgName.js
  optimizeImages/lib/utils/removeExtension.js
  optimizeImages/optimizeImages.js
  package-lock.json
  package.json
  src/__tests__/constants.ts
  src/app/components/course-card/course-card.tsx
  src/app/components/date-lang/date-lang.test.tsx
  src/app/components/date-lang/date-lang.tsx
  src/app/components/logo-wrapper/logo-wrapper.tsx
  src/app/components/school-menu/school-item.tsx
  src/features/about-video/about-video.tsx
  src/features/about/components/info-grid/info-grid.tsx
  src/features/course-main/course-main.tsx
  src/features/courses/main/main.test.tsx
  src/features/courses/main/main.tsx
  src/features/courses/mentors/mentors.test.tsx
  src/features/courses/mentors/mentors.tsx
  src/features/home/about/about.tsx
  src/features/home/alumni/alumni.tsx
  src/features/home/community/community.tsx
  src/features/home/contribute/contribute.tsx
  src/features/home/merch/merch.tsx
  src/features/home/numbers/numbers.tsx
  src/features/home/pictures/pictures.tsx
  src/features/home/school/school.tsx
  src/features/home/speakers/speakers.tsx
  src/features/home/support/support.tsx
  src/features/image/constants.ts
  src/features/image/image.tsx
  src/features/image/index.ts
  src/features/image/types.ts
  src/features/image/utils/convertToWebp.ts
  src/features/image/utils/generateSizes.ts
  src/features/image/utils/generateSrcSet.ts
  src/features/not-found/not-found.tsx
  src/features/study-path/components/stage-card/image/image.tsx
  src/features/study-path/components/stage-card/logo-icon/logo-icon.tsx
  src/features/trainers/trainer-card.tsx
  src/features/training-program/training-program.tsx
  vitest.config.ts
Labels: feature, high priority

#148 Refactor/update dzmitry photo
  src/assets/mentors/d-yarmoshkin.png
  src/assets/mentors/d-yarmoshkin.webp
  src/features/trainers/react-en.data.ts
Labels: refactor, high priority

#140 fix: update course start dates and links
  src/app/services/data/courses.data.ts
  src/features/course-main/course-main.test.tsx
  src/features/course-main/course-main.tsx
  src/features/home/courses/courses.scss
  src/features/home/courses/courses.test.tsx
  src/features/home/courses/courses.tsx
  src/icons/angular-icon.tsx
  src/icons/aws.tsx
  src/icons/html-icon.tsx
  src/icons/index.tsx
  src/icons/js-frontend-icon.tsx
  src/icons/js-secondary
  src/icons/nodejs-icon.tsx
  src/icons/react-icon.tsx
  src/pages/nodejs.tsx
Labels: bug, high priority

#163 feature/add stylelint check to ci/cd pipeline
  .github/workflows/main.yml
Labels: feature, high priority

#162 feature/change vite to convert css classes to camel case
  vite.config.ts
Labels: feature, high priority
