Repository rolling-scopes/site, pull requests merged in 2024-10, with the labels that each got.

#577 522-refactor: Widget community
  dev-data/community-media.data.tsx
  dev-data/index.ts
  src/pages/community.tsx
  src/shared/ui/social-media-item/index.ts
  src/shared/ui/social-media-item/social-media-item.module.scss
  src/shared/ui/social-media-item/social-media-item.test.tsx
  src/shared/ui/social-media-item/social-media-item.tsx
  src/shared/ui/social-media/index.ts
  src/widgets/community-media/index.ts
  src/widgets/community-media/ui/community-media.module.scss
  src/widgets/community-media/ui/community-media.test.tsx
  src/widgets/community-media/ui/community-media.tsx
  src/widgets/community/community.test.tsx
  src/widgets/community/index.ts
  src/widgets/community/ui/community.scss
  src/widgets/community/ui/community.tsx
  src/widgets/pictures/ui/pictures.tsx
Labels: refactor, preview

#588 587-feat: Update course trainers
  dev-data/javascript-en.data.ts
  src/shared/assets/mentors/h-pratasevich.webp
Labels: feature, preview

#573 347-refactor: Fsd widget events
  src/shared/constants.ts
  src/widgets/events/constants.ts
  src/widgets/events/ui/events.module.scss
  src/widgets/events/ui/events.test.tsx
  src/widgets/events/ui/events.tsx
Labels: refactor, preview

#579 548-refactor: Widget mentoring
  dev-data/index.ts
  dev-data/mentoring.data.ts
  src/widgets/mentoring/mentoring.test.tsx
  src/widgets/mentoring/ui/mentoring.module.scss
  src/widgets/mentoring/ui/mentoring.scss
  src/widgets/mentoring/ui/mentoring.test.tsx
  src/widgets/mentoring/ui/mentoring.tsx
Labels: refactor, preview

#600 597-feat: Update course trainers
  dev-data/angular.data.ts
  dev-data/javascript-en.data.ts
  dev-data/javascript-ru.data.ts
  src/shared/assets/mentors/d-saripov.webp
  src/shared/assets/mentors/l-cool.webp
  src/shared/assets/mentors/n-lebedeva.webp
Labels: feature, preview

#575 574-refactor: List component
  dev-data/courses-data.types.ts
  dev-data/training-program.data.tsx
  src/pages/javascript-en.tsx
  src/shared/types.ts
  src/shared/ui/list/index.ts
  src/shared/ui/list/list.module.scss
  src/shared/ui/list/list.test.tsx
  src/shared/ui/list/list.tsx
  src/widgets/study-path/ui/stage-card/stage-card.tsx
  src/widgets/study-path/ui/stage-card/stage-card.types.ts
  src/widgets/study-path/ui/stages/stages.tsx
  src/widgets/study-path/ui/study-path.tsx
Labels: refactor, preview

#608 607-fix: Falling test
  src/widgets/upcoming-courses/ui/upcoming-courses.test.tsx
Labels: bug, high priority

#593 fix: 590 - get rid of orphans
  src/app/styles/index.scss
Labels: preview

#591 558-refactor: Widget pictures
  dev-data/index.ts
  dev-data/pictures.data.tsx
  dev-data/slider-photos.data.ts
  package-lock.json
  playwright.config.ts
  src/app/app.tsx
  src/app/styles/index.scss
  src/main.tsx
  src/shared/hooks/use-course-by-title/use-course-by-title.ts
  src/shared/hooks/use-course-by-title/utils/is-course.ts
  src/shared/ui/logo/logo.tsx
  src/shared/ui/main-title/main-title.tsx
  src/widgets/pictures/pictures.test.tsx
  src/widgets/pictures/ui/pictures.module.scss
  src/widgets/pictures/ui/pictures.scss
  src/widgets/pictures/ui/pictures.test.tsx
  src/widgets/pictures/ui/pictures.tsx
Labels: refactor, preview

#598 562-refactor: Widget requirements
  dev-data/index.ts
  dev-data/requirements.data.ts
  src/widgets/requirements/requirements.test.tsx
  src/widgets/requirements/ui/requirements.module.scss
  src/widgets/requirements/ui/requirements.scss
  src/widgets/requirements/ui/requirements.test.tsx
  src/widgets/requirements/ui/requirements.tsx
Labels: refactor, preview

#595 549-refactor: Widget mentors
  src/app/const/index.ts
  src/widgets/mentors/ui/mentors.module.scss
  src/widgets/mentors/ui/mentors.scss
  src/widgets/mentors/ui/mentors.test.tsx
  src/widgets/mentors/ui/mentors.tsx
  src/widgets/school-menu/ui/school-menu.tsx
Labels: refactor, preview

#543 532-refactor: FSD: Widget Course main
  dev-data/hero-course.data.ts
  dev-data/index.ts
  src/app/const/index.ts
  src/app/routes.tsx
  src/entities/course/api/loader.ts
  src/entities/course/index.ts
  src/pages/angular.tsx
  src/pages/aws-developer.tsx
  src/pages/aws-devops.tsx
  src/pages/aws-fundamentals.tsx
  src/pages/javascript-en.tsx
  src/pages/javascript-preschool-ru.tsx
  src/pages/javascript-ru.tsx
  src/pages/nodejs.tsx
  src/pages/react.tsx
  src/shared/assets/icons/js-secondary.webp
  src/shared/ui/main-title/main-title.module.scss
  src/shared/ui/main-title/main-title.tsx
  src/widgets/course-main/course-main.module.scss
  src/widgets/course-main/index.ts
  src/widgets/course-main/utils/has-day.ts
  src/widgets/hero-course/helpers/get-course-status.test.ts
  src/widgets/hero-course/helpers/get-course-status.ts
  src/widgets/hero-course/helpers/has-day.test.ts
  src/widgets/hero-course/helpers/has-day.ts
  src/widgets/hero-course/index.ts
  src/widgets/hero-course/ui/hero-course.module.scss
  src/widgets/hero-course/ui/hero-course.test.tsx
  src/widgets/hero-course/ui/hero-course.tsx
Labels: refactor, preview

#604 568-refactor: Widget trainers
  src/widgets/trainers/constants.ts
  src/widgets/trainers/trainers.test.tsx
  src/widgets/trainers/ui/trainers.module.scss
  src/widgets/trainers/ui/trainers.scss
  src/widgets/trainers/ui/trainers.test.tsx
  src/widgets/trainers/ui/trainers.tsx
Labels: refactor, preview

#611 610-feat: Mobile menu test
  src/app/styles/_constants.scss
  src/shared/__tests__/visual/main.spec.ts
  src/shared/__tests__/visual/utils/index.ts
  src/shared/__tests__/visual/utils/viewports.ts
Labels: preview

#576 489-refactor: Widget About
  dev-data/about-course.data.tsx
  dev-data/courses-data.types.ts
  dev-data/index.ts
  src/app/styles/_constants.scss
  src/pages/angular.tsx
  src/pages/aws-developer.tsx
  src/pages/aws-devops.tsx
  src/pages/aws-fundamentals.tsx
  src/pages/javascript-en.tsx
  src/pages/javascript-preschool-ru.tsx
  src/pages/javascript-ru.tsx
  src/pages/nodejs.tsx
  src/pages/react.tsx
  src/shared/constants.ts
  src/shared/types.ts
  src/widgets/about-course/index.ts
  src/widgets/about-course/ui/about-course-grid/about-course-grid.module.scss
  src/widgets/about-course/ui/about-course-grid/about-course-grid.test.tsx
  src/widgets/about-course/ui/about-course-grid/about-course-grid.tsx
  src/widgets/about-course/ui/about-course/about-course.module.scss
  src/widgets/about-course/ui/about-course/about-course.test.tsx
  src/widgets/about-course/ui/about-course/about-course.tsx
  src/widgets/about/about.test.tsx
  src/widgets/about/index.ts
  src/widgets/about/ui/about.scss
  src/widgets/about/ui/about.tsx
  src/widgets/about/ui/info-grid/info-grid.scss
  src/widgets/about/ui/info-grid/info-grid.test.tsx
  src/widgets/about/ui/info-grid/info-grid.tsx
  src/widgets/hero-course/ui/hero-course.tsx
Labels: refactor, preview

#605 603-feat: Discord note
  dev-data/widget-communication.data.ts
  src/widgets/communication/ui/communication.tsx
Labels: preview

#601 523-refactor: Widget contribute
  .gitignore
  dev-data/contribute-options.data.ts
  dev-data/index.ts
  src/app/const/index.ts
  src/widgets/contribute/contribute.test.tsx
  src/widgets/contribute/ui/contribute.module.scss
  src/widgets/contribute/ui/contribute.scss
  src/widgets/contribute/ui/contribute.test.tsx
  src/widgets/contribute/ui/contribute.tsx
  src/widgets/option-item/index.ts
  src/widgets/option-item/ui/option-item.module.scss
  src/widgets/option-item/ui/option-item.test.tsx
  src/widgets/option-item/ui/option-item.tsx
Labels: refactor, preview

#599 550-refactor: Widget mentors wanted
  src/app/const/index.ts
  src/pages/angular.tsx
  src/pages/home.tsx
  src/widgets/mentors-wanted-course/index.ts
  src/widgets/mentors-wanted-course/ui/mentors-wanted-course.module.scss
  src/widgets/mentors-wanted-course/ui/mentors-wanted-course.test.tsx
  src/widgets/mentors-wanted-course/ui/mentors-wanted-course.tsx
  src/widgets/mentors-wanted/ui/mentors-wanted.module.scss
  src/widgets/mentors-wanted/ui/mentors-wanted.test.tsx
  src/widgets/mentors-wanted/ui/mentors-wanted.tsx
  src/widgets/mentors/index.ts
  src/widgets/mentors/ui/mentors.module.scss
  src/widgets/mentors/ui/mentors.tsx
Labels: refactor, draft, preview

#618 617-feat: Update js en trainers
  dev-data/javascript-en.data.ts
  src/shared/assets/mentors/n-volkova.webp
Labels: feature, preview

#616 613-feat: Update communication section
  dev-data/communication.data.ts
  dev-data/index.ts
  dev-data/widget-communication.data.ts
  src/widgets/communication/ui/communication.module.scss
  src/widgets/communication/ui/communication.test.tsx
  src/widgets/communication/ui/communication.tsx
Labels: feature, preview

#622 621-feat: Change js en docs link
  dev-data/communication.data.ts
  dev-data/index.ts
  src/widgets/communication/ui/communication.tsx
Labels: feature, preview
