Repository rolling-scopes/site, pull requests merged in 2025-04, with the labels that each got.

#834 821-test: Add unit test for component faq
  dev-data/faq.data.ts
  dev-data/index.ts
  src/shared/__tests__/constants.ts
  src/views/javascript-preschool-ru.tsx
  src/widgets/faq/index.tsx
  src/widgets/faq/types.ts
  src/widgets/faq/ui/faq.test.tsx
  src/widgets/faq/ui/faq.tsx
Labels: preview

#816 815-fix: Search result links incorrect color
  next.config.ts
  src/app/docs/[lang]/[...slug]/page.tsx
  src/app/docs/[lang]/layout.tsx
  src/app/docs/[lang]/page.tsx
  src/app/docs/components/docs-content/docs-content.tsx
  src/app/docs/components/docs-layout/docs-layout.tsx
  src/app/docs/components/docs-menu/docs-menu.module.scss
  src/app/docs/components/docs-menu/docs-menu.tsx
  src/app/docs/components/search/search.module.scss
  src/core/base-layout/components/header/nav-item/nav-item.tsx
Labels: preview

#845 832-refactor: Mentorship folder
  dev-data/index.ts
  dev-data/mentorship-data.types.ts
  package-lock.json
  src/views/mentorship/mentorship.tsx
  src/views/mentorship/ui/mentors-after-register/index.ts
  src/widgets/mentorship-activities/index.ts
  src/widgets/mentorship-activities/ui/activity-card/activity-card.module.scss
  src/widgets/mentorship-activities/ui/activity-card/activity-card.test.tsx
  src/widgets/mentorship-activities/ui/activity-card/activity-card.tsx
  src/widgets/mentorship-activities/ui/mentor-activities/mentor-activities.module.scss
  src/widgets/mentorship-activities/ui/mentor-activities/mentor-activities.test.tsx
  src/widgets/mentorship-activities/ui/mentor-activities/mentor-activities.tsx
  src/widgets/mentorship-after-register/index.ts
  src/widgets/mentorship-after-register/ui/mentorship-after-register.module.scss
  src/widgets/mentorship-after-register/ui/mentorship-after-register.test.tsx
  src/widgets/mentorship-after-register/ui/mentorship-after-register.tsx
  src/widgets/mentorship-courses/mentorship-courses.module.scss
  src/widgets/mentorship-courses/mentorship-courses.test.tsx
  src/widgets/mentorship-courses/mentorship-courses.tsx
  src/widgets/mentorship-details/mentorship-details.module.scss
  src/widgets/mentorship-details/mentorship-details.tsx
  src/widgets/mentorship-details/mentoship-details.test.tsx
  src/widgets/mentorship-hero/index.ts
  src/widgets/mentorship-hero/ui/mentorship-hero.module.scss
  src/widgets/mentorship-hero/ui/mentorship-hero.test.tsx
  src/widgets/mentorship-hero/ui/mentorship-hero.tsx
Labels: refactor, preview, ⚔️padawans

#848 827-refactor: Fsd core components
  src/core/base-layout/base-layout.test.tsx
  src/core/base-layout/components/index.ts
  src/widgets/footer/footer.scss
  src/widgets/footer/footer.test.tsx
  src/widgets/footer/footer.tsx
  src/widgets/footer/index.ts
  src/widgets/footer/ui/about-list.tsx
  src/widgets/footer/ui/copyright.tsx
  src/widgets/footer/ui/desktop-view.tsx
  src/widgets/header/header.module.scss
  src/widgets/header/header.test.tsx
  src/widgets/header/header.tsx
  src/widgets/header/index.ts
  src/widgets/header/ui/burger/burger.module.scss
  src/widgets/header/ui/burger/burger.tsx
  src/widgets/header/ui/dropdown/dropdown-wrapper.module.scss
  src/widgets/header/ui/dropdown/dropdown-wrapper.tsx
  src/widgets/header/ui/nav-item/nav-item.module.scss
  src/widgets/header/ui/nav-item/nav-item.tsx
  src/widgets/partnered/index.ts
  src/widgets/partnered/partnered.scss
  src/widgets/partnered/partnered.test.tsx
  src/widgets/partnered/partnered.tsx
Labels: refactor, preview, ⚔️padawans

#851 831-refactor: Fix filenames to kebab case
  dev-data/aws-dev.data.ts
  dev-data/aws-fundamentals.data.ts
  dev-data/communication.data.ts
  dev-data/course-titles.data.ts
  dev-data/index.ts
  dev-data/mentorship-data.types.ts
  dev-data/mentorship.data.ts
  dev-data/pre-school.data.ts
  dev-data/required.data.ts
  dev-data/training-program.data.tsx
  eslint.config.js
  package-lock.json
  package.json
  src/app/docs/[lang]/[...slug]/page.tsx
  src/app/docs/[lang]/layout.tsx
  src/app/docs/[lang]/page.tsx
  src/app/docs/components/docs-content/docs-content.tsx
  src/app/docs/components/docs-menu/docs-menu.tsx
  src/app/docs/components/search/search.tsx
  src/app/docs/mocked-search.ts
  src/app/docs/utils/fetch-markdown-content.ts
  src/app/docs/utils/fetch-menu.ts
  src/app/layout.tsx
  src/entities/course/helpers/sync-with-api-data.ts
  src/entities/course/ui/course-card/course-card.test.tsx
  src/entities/course/ui/course-item/course-item.test.tsx
  src/shared/helpers/convert-to-webp.ts
  src/shared/helpers/day-js.ts
  src/shared/helpers/get-actual-data.test.ts
  src/shared/helpers/get-actual-data.ts
  src/shared/helpers/get-course-date.test.ts
  src/shared/helpers/get-course-date.ts
  src/shared/helpers/is-valid-url.ts
  src/shared/icons/index.tsx
  src/shared/icons/linkedin.tsx
  src/shared/ui/date-simple/date-simple.test.tsx
  src/shared/ui/date-simple/date-simple.tsx
  src/shared/ui/short-info-panel/short-info-panel.test.tsx
  src/shared/ui/short-info-panel/short-info-panel.tsx
  src/views/mentorship/helpers/transform-courses-to-mentorship.ts
  src/widgets/courses/ui/courses.tsx
  src/widgets/events/constants.ts
  src/widgets/hero-course/helpers/get-course-status.test.ts
  src/widgets/hero-course/helpers/get-course-status.ts
  src/widgets/hero-course/ui/hero-course.tsx
  src/widgets/mentorship-courses/mentorship-courses.tsx
  src/widgets/upcoming-courses/ui/upcoming-courses.test.tsx
  src/widgets/upcoming-courses/ui/upcoming-courses.tsx
Labels: low priority, preview, ⚔️padawans

#854 732-feat: Integration with Contentful
  .env.example
  .github/workflows/main.yml
  .github/workflows/preview-create.yml
  .github/workflows/production.yml
  .github/workflows/visual-testing-on-comment.yml
  .github/workflows/visual-testing-on-push.yml
  dev-data/angular.data.ts
  dev-data/aws-dev.data.ts
  dev-data/aws-devops.data.ts
  dev-data/aws-fundamentals.data.ts
  dev-data/index.ts
  dev-data/javascript-en.data.ts
  dev-data/javascript-ru.data.ts
  dev-data/nodejs.data.ts
  dev-data/pre-school.data.ts
  dev-data/react-en.data.ts
  dev-data/react-ru.data.ts
  env.d.ts
  package-lock.json
  package.json
  src/core/api/app-api.ts
  src/entities/course/@x/trainer/index.ts
  src/entities/course/constants.ts
  src/entities/course/types.ts
  src/entities/trainer/api/trainer-api.ts
  src/entities/trainer/helpers/transform-trainers.ts
  src/entities/trainer/index.ts
  src/entities/trainer/model/store.ts
  src/entities/trainer/types.ts
  src/shared/api/api-base-class.ts
  src/shared/api/api.ts
  src/shared/constants.ts
  src/shared/helpers/is-api-error.ts
  src/shared/helpers/log-request.ts
  src/shared/helpers/prepare-https-url.ts
  src/shared/helpers/stringify-json-safe.ts
  src/shared/types.ts
  src/shared/types/contentful/index.ts
  src/shared/types/contentful/type-contributor.ts
  src/shared/types/contentful/type-course.ts
  src/shared/types/contentful/type-home-page.ts
  src/shared/types/index.ts
  src/shared/types/types.ts
  src/views/angular.tsx
  src/views/aws-developer.tsx
  src/views/aws-devops.tsx
  src/views/aws-fundamentals.tsx
  src/views/javascript-en.tsx
  src/views/javascript-preschool-ru.tsx
  src/views/javascript-ru.tsx
  src/views/nodejs.tsx
  src/views/react.tsx
Labels: feature, high priority, preview

#860 856-feat: Update preschool description
  dev-data/about-course.data.tsx
  dev-data/faq.data.ts
  dev-data/training-program.data.tsx
  src/views/javascript-preschool-ru.tsx
  src/widgets/certification/ui/certification.tsx
Labels: feature, high priority, preview
