Repository rolling-scopes/site, pull requests merged in 2025-05, with the labels that each got.

#846 826-refactor: Core shared
  dev-data/about-course.data.tsx
  dev-data/contribute-options.data.ts
  dev-data/courses.data.ts
  dev-data/donate-options.data.ts
  dev-data/mentors-register.data.ts
  dev-data/mentorship-data.types.ts
  dev-data/mentorship.data.ts
  dev-data/requirements.data.ts
  dev-data/school-menu-links.ts
  dev-data/study-path.data.ts
  src/app/docs/components/lang-switcher/lang-switcher.tsx
  src/core/base-layout/base-layout.test.tsx
  src/core/const/index.ts
  src/core/services/api/index.ts
  src/core/types/route.types.ts
  src/entities/trainer/api/trainer-api.ts
  src/entities/trainer/types.ts
  src/shared/__tests__/constants.ts
  src/shared/__tests__/utils/render-with-router/render-with-router.tsx
  src/shared/__tests__/visual/community.spec.ts
  src/shared/__tests__/visual/courses.spec.ts
  src/shared/__tests__/visual/main.spec.ts
  src/shared/__tests__/visual/not-found.spec.ts
  src/shared/constants.ts
  src/shared/types/index.ts
  src/shared/ui/logo/logo.tsx
  src/views/angular.tsx
  src/views/javascript-en.tsx
  src/views/javascript-ru.tsx
  src/views/mentorship/constants.ts
  src/widgets/about-community/ui/about-community.tsx
  src/widgets/about-school/ui/about-school.tsx
  src/widgets/breadcrumbs/types.ts
  src/widgets/breadcrumbs/ui/breadcrumbs.test.tsx
  src/widgets/breadcrumbs/ui/breadcrumbs.tsx
  src/widgets/footer/ui/about-list.tsx
  src/widgets/header/header.tsx
  src/widgets/header/ui/nav-item/nav-item.tsx
  src/widgets/hero-course/helpers/get-course-status.ts
  src/widgets/mentors-wanted-course/ui/mentors-wanted-course.test.tsx
  src/widgets/mentors-wanted/ui/mentors-wanted.test.tsx
  src/widgets/mentors-wanted/ui/mentors-wanted.tsx
  src/widgets/merch/ui/merch.tsx
  src/widgets/mobile-view/ui/mobile-view.tsx
  src/widgets/upcoming-courses/ui/upcoming-courses.tsx
Labels: refactor, preview, ⚔️padawans

#858 857-refactor: Angular course data update
  dev-data/about-course.data.tsx
  dev-data/courses.data.ts
  dev-data/required.data.ts
  dev-data/training-program.data.tsx
  src/widgets/training-program/ui/training-program.test.tsx
Labels: high priority, preview

#879 870-fix: Remove invisible black arrows
  src/shared/ui/link-custom/link-custom.test.tsx
  src/shared/ui/link-custom/link-custom.tsx
Labels: preview

#881 819-test: Add unit test for component onboard links
  src/widgets/mentors-docs/ui/onboard-links/onboard-links.test.tsx
  src/widgets/mentors-docs/ui/onboard-links/onboard-links.tsx
Labels: preview

#862 861-feat: Move course data to contentful
  .env.example
  .github/workflows/main.yml
  .github/workflows/preview-create.yml
  .github/workflows/production.yml
  .github/workflows/visual-testing-on-comment.yml
  .github/workflows/visual-testing-on-push.yml
  dev-data/courses.data.ts
  dev-data/index.ts
  env.d.ts
  src/core/api/app-api.ts
  src/core/base-layout/base-layout.tsx
  src/entities/course/api/course-api.ts
  src/entities/course/constants.ts
  src/entities/course/helpers/build-course-url.ts
  src/entities/course/helpers/sync-api-courses-schedule.ts
  src/entities/course/helpers/transform-courses.ts
  src/entities/course/index.ts
  src/entities/course/model/store.ts
  src/entities/course/types.ts
  src/entities/trainer/helpers/transform-trainers.ts
  src/shared/__tests__/constants.ts
  src/shared/__tests__/setup-tests.tsx
  src/shared/api/api-base-class.ts
  src/shared/assets/icons/aws-white.svg
  src/shared/assets/icons/javascript-black.svg
  src/shared/assets/icons/node-js-black.svg
  src/shared/helpers/find-asset-image-by-id.ts
  src/shared/helpers/get-actual-data.test.ts
  src/shared/helpers/get-course-title.ts
  src/shared/hooks/use-course-by-title/utils/select-course.ts
  src/shared/types/contentful/type-course.ts
  src/widgets/about-course/ui/about-course/about-course.tsx
  src/widgets/communication/ui/communication.test.tsx
  src/widgets/communication/ui/communication.tsx
  src/widgets/courses/ui/courses.tsx
  src/widgets/footer/ui/desktop-view.tsx
  src/widgets/hero-course/ui/hero-course.tsx
  src/widgets/mentorship-courses/mentorship-courses.tsx
  src/widgets/upcoming-courses/ui/upcoming-courses.tsx
Labels: feature, high priority, preview

#780 623-docs: Contributing page
  README.md
  readme/README.md
  readme/contributing.md
Labels: preview

#865 863-feat: Add ai course page
  dev-data/about-course.data.tsx
  dev-data/course-titles.data.ts
  dev-data/index.ts
  dev-data/required.data.ts
  dev-data/training-program.data.tsx
  src/app/courses/aws-ai/page.tsx
  src/entities/course/constants.ts
  src/shared/assets/icons/aws-ai.svg
  src/shared/constants.ts
  src/views/aws-ai.tsx
  src/widgets/breadcrumbs/constants.ts
  src/widgets/certification/ui/certification.tsx
Labels: feature, high priority, preview

#828 638-feat: Add registration end date to the course pages
  src/entities/course/ui/course-card/course-card.tsx
  src/entities/course/ui/course-item/course-item.tsx
  src/shared/constants.ts
  src/shared/ui/date-simple/date-simple.test.tsx
  src/shared/ui/date-simple/date-simple.tsx
  src/shared/ui/short-info-panel/short-info-panel.module.scss
  src/shared/ui/short-info-panel/short-info-panel.test.tsx
  src/shared/ui/short-info-panel/short-info-panel.tsx
Labels: feature, preview, ⚔️padawans

#900 899-feat: Language trainer
  src/views/aws-ai.tsx
Labels: bug, high priority

#886 841-fix: Docs sidebar overlap
  src/app/docs/components/docs-menu/docs-menu.module.scss
Labels: preview

#893 876-fix: Update paddings for wide screens
  src/core/styles/_mixins.scss
  src/widgets/footer/footer.scss
  src/widgets/header/header.module.scss
Labels: preview

#872 871-refactor: Refactor youtube api
  .env.example
  .github/workflows/main.yml
  .github/workflows/preview-create.yml
  .github/workflows/production.yml
  .github/workflows/visual-testing-on-comment.yml
  .github/workflows/visual-testing-on-push.yml
  env.d.ts
  package-lock.json
  package.json
  src/core/api/app-api.ts
  src/entities/mentor/api/mentor-api.ts
  src/entities/mentor/constants.ts
  src/entities/mentor/helpers/transform-mentor-videos.ts
  src/entities/mentor/index.ts
  src/entities/mentor/model/store.ts
  src/entities/mentor/types.ts
  src/shared/api/api-base-class.ts
  src/shared/api/api.ts
  src/shared/constants.ts
  src/shared/helpers/filter-youtube-private-videos.ts
  src/shared/helpers/log-request.ts
  src/shared/types/types.ts
  src/shared/ui/video-playlist-with-player/video-playlist-with-player.test.tsx
  src/shared/ui/video-playlist-with-player/video-playlist-with-player.tsx
  src/widgets/mentors-feedback/ui/mentors-feedback.tsx
  src/widgets/mentors-feedback/ui/mentors-playlist/mentor-talks-video-playlist-with-player.tsx
Labels: refactor, preview

#898 897-fix: Remove repeated footer sections
  src/widgets/footer/footer.scss
Labels: bug, high priority, preview
