Repository rolling-scopes/site, pull requests merged in 2025-03, with the labels that each got.

#789 763-refactor: Display mentorship dates
  dev-data/courses.data.ts
  src/entities/course/constants.ts
  src/entities/course/helpers/sync-with-api-data.ts
  src/entities/course/types.ts
  src/entities/course/ui/course-card/course-card.test.tsx
  src/entities/course/ui/course-card/course-card.tsx
  src/entities/course/ui/course-item/course-item.module.scss
  src/entities/course/ui/course-item/course-item.test.tsx
  src/entities/course/ui/course-item/course-item.tsx
  src/shared/__tests__/constants.ts
  src/shared/constants.ts
  src/shared/helpers/getActualData.test.ts
  src/shared/helpers/getCourseDate.ts
  src/shared/ui/date-lang/date-lang.tsx
  src/shared/ui/date-lang/index.ts
  src/shared/ui/date-simple/date-simple.module.scss
  src/shared/ui/date-simple/date-simple.test.tsx
  src/shared/ui/date-simple/date-simple.tsx
  src/shared/ui/date-simple/index.ts
  src/shared/ui/date-start/index.ts
  src/shared/ui/date-start/ui/date-start.tsx
  src/shared/ui/short-info-panel/index.ts
  src/shared/ui/short-info-panel/short-info-panel.module.scss
  src/shared/ui/short-info-panel/short-info-panel.test.tsx
  src/shared/ui/short-info-panel/short-info-panel.tsx
  src/views/mentorship/ui/mentorship-courses/mentorship-courses.tsx
  src/widgets/hero-course/ui/hero-course.tsx
Labels: preview

#797 795-fix: Fix slider button
  src/core/styles/index.scss
Labels: bug, preview

#773 771-feat: Mentorship post release updates: Modal improvements
  src/core/styles/_constants.scss
  src/entities/mentor/ui/mentor-feedback-card/mentor-feedback-card.test.tsx
  src/shared/constants.ts
  src/shared/ui/modal/modal.module.scss
  src/shared/ui/modal/modal.test.tsx
  src/shared/ui/modal/modal.tsx
Labels: feature, preview

#811 796-refactor: Change gray colors palette
  src/core/styles/_constants.scss
Labels: preview

#812 794-fix: Dark color of icons in footer
  src/shared/assets/icons/javascript-black.svg
  src/widgets/mobile-view/ui/mobile-view.tsx
Labels: bug, preview
