Repository rolling-scopes/site, pull requests merged in 2025-02, with the labels that each got.

#775 remove epam logo
  src/core/base-layout/components/partnered/partnered.tsx
Labels: preview

#708 707-refactor: Global column class
  src/app/docs/components/docs-menu/docs-menu.module.scss
  src/core/base-layout/components/header/burger/burger.module.scss
  src/core/base-layout/components/header/header.module.scss
  src/core/styles/index.scss
  src/entities/mentor/ui/mentor-feedback-card/mentor-feedback-card.module.scss
  src/shared/ui/link-custom/link-custom.module.scss
  src/shared/ui/modal/modal.module.scss
  src/shared/ui/video-playlist-with-player/playlist/playlist.module.scss
  src/views/mentorship/mentorship-hero/ui/mentorship-hero.module.scss
  src/views/mentorship/ui/mentor-activities/ui/activity-card/activity-card.module.scss
  src/widgets/about-community/ui/about-community.module.scss
  src/widgets/about-video/ui/about-video.module.scss
  src/widgets/community-media/ui/community-media.module.scss
  src/widgets/contribute/ui/contribute.module.scss
  src/widgets/contribute/ui/contribute.tsx
  src/widgets/events/ui/events.module.scss
  src/widgets/events/ui/events.tsx
  src/widgets/mentors-wanted-course/ui/mentors-wanted-course.module.scss
  src/widgets/mentors-wanted-course/ui/mentors-wanted-course.tsx
  src/widgets/mentors-wanted/ui/mentors-wanted.module.scss
  src/widgets/merch/ui/merch.module.scss
  src/widgets/speakers/ui/speakers.module.scss
  src/widgets/speakers/ui/speakers.tsx
  src/widgets/study-with-us/ui/study-with-us.module.scss
  src/widgets/study-with-us/ui/study-with-us.tsx
  src/widgets/support/ui/support.module.scss
  src/widgets/support/ui/support.tsx
  src/widgets/training-program/ui/training-program.module.scss
Labels: refactor, preview

#793 792-fix: Windows npm run test
  vitest.config.ts
Labels: preview

#778 777-feat: Add debug configs for VS Code
  .vscode/launch.json
  readme/debugging.md
Labels: feature, preview

#770 769-refactor: Mentorship post release updates: Typography
  src/app/docs/components/docs-menu/docs-menu.module.scss
  src/app/docs/components/search/search.module.scss
  src/core/base-layout/components/header/burger/burger.module.scss
  src/core/base-layout/components/header/dropdown/dropdown-wrapper.module.scss
  src/core/base-layout/components/header/header.module.scss
  src/core/base-layout/components/header/nav-item/nav-item.module.scss
  src/core/styles/_constants.scss
  src/core/styles/_mixins.scss
  src/core/styles/index.scss
  src/entities/course/ui/course-card/course-card.module.scss
  src/entities/course/ui/course-item/course-item.module.scss
  src/entities/course/ui/course-item/course-item.tsx
  src/entities/event/ui/event-card/event-card.module.scss
  src/entities/mentor/ui/mentor-feedback-card/mentor-feedback-card.module.scss
  src/entities/mentor/ui/mentor-feedback-card/mentor-feedback-card.tsx
  src/entities/trainer/ui/trainers-card/trainer-card.module.scss
  src/shared/ui/date-lang/date-lang.module.scss
  src/shared/ui/link-custom/link-custom.module.scss
  src/shared/ui/link-custom/link-custom.tsx
  src/shared/ui/list/list.module.scss
  src/shared/ui/modal/modal.module.scss
  src/shared/ui/paragraph/paragraph.module.scss
  src/shared/ui/section-label/section-label.module.scss
  src/shared/ui/social-media-item/social-media-item.module.scss
  src/shared/ui/social-media-item/social-media-item.tsx
  src/shared/ui/subtitle/subtitle.module.scss
  src/shared/ui/subtitle/subtitle.test.tsx
  src/shared/ui/subtitle/subtitle.tsx
  src/shared/ui/video-playlist-with-player/playlist/playlist.module.scss
  src/shared/ui/widget-title/widget-title.module.scss
  src/views/mentorship/mentorship-hero/ui/mentorship-hero.module.scss
  src/views/mentorship/mentorship-hero/ui/mentorship-hero.tsx
  src/views/mentorship/ui/mentor-activities/ui/activity-card/activity-card.module.scss
  src/views/mentorship/ui/mentor-activities/ui/activity-card/activity-card.tsx
  src/views/mentorship/ui/mentors-after-register/ui/mentors-after-register.tsx
  src/widgets/about-course/ui/about-course-grid/about-course-grid.module.scss
  src/widgets/about-video/ui/about-video.module.scss
  src/widgets/benefits/ui/benefits/benefits.module.scss
  src/widgets/breadcrumbs/ui/breadcrumbs.module.scss
  src/widgets/communication/ui/communication.module.scss
  src/widgets/faq/ui/faq.module.scss
  src/widgets/general/ui/general.module.scss
  src/widgets/hero-page/ui/hero-page.tsx
  src/widgets/member-activity/ui/stage-card/stage-card.scss
  src/widgets/member-activity/ui/stage-card/step/step.scss
  src/widgets/mentors-docs/ui/doc-detail/ui/doc-detail.tsx
  src/widgets/mentors-docs/ui/onboard-links/onboard-links.module.scss
  src/widgets/mentors-register/ui/mentors-register.module.scss
  src/widgets/mentors-register/ui/mentors-register.tsx
  src/widgets/mobile-view/ui/mobile-view.module.scss
  src/widgets/numbers/ui/info-cell/info-cell.module.scss
  src/widgets/places/ui/places/places.module.scss
  src/widgets/principles/ui/principle-card/principle-card.module.scss
  src/widgets/school-menu/ui/school-item/school-item.module.scss
  src/widgets/speakers/ui/speakers.tsx
Labels: refactor, preview

#801 feat: update links to doc source
  src/app/docs/constants.ts
  src/app/docs/utils/fetchMenu.ts
Labels: preview
