Repository rolling-scopes/site, pull requests merged in 2025-01, with the labels that each got.

#681 680-refactor: Lang props
  dev-data/courses.data.ts
  dev-data/index.ts
  src/app/courses/angular/page.tsx
  src/app/courses/aws-cloud-developer/page.tsx
  src/app/courses/aws-devops/page.tsx
  src/app/courses/aws-fundamentals/page.tsx
  src/app/courses/javascript-preschool-ru/page.tsx
  src/app/courses/javascript-ru/page.tsx
  src/app/courses/javascript/page.tsx
  src/app/courses/nodejs/page.tsx
  src/app/courses/reactjs/page.tsx
  src/entities/course/types.ts
  src/entities/course/ui/course-card/course-card.test.tsx
  src/entities/course/ui/course-item/course-item.test.tsx
  src/entities/course/ui/course-item/course-item.tsx
  src/shared/__tests__/constants.ts
  src/shared/__tests__/setup-tests.tsx
  src/shared/helpers/get-course-language.ts
  src/shared/helpers/getActualData.test.ts
  src/shared/helpers/is-training-program.ts
  src/shared/ui/date-lang/date-lang.test.tsx
  src/shared/ui/date-lang/date-lang.tsx
  src/views/angular.tsx
  src/views/aws-developer.tsx
  src/views/aws-devops.tsx
  src/views/aws-fundamentals.tsx
  src/views/javascript-en.tsx
  src/views/javascript-preschool-ru.tsx
  src/views/javascript-ru.tsx
  src/views/nodejs.tsx
  src/views/react.tsx
  src/widgets/about-course/ui/about-course/about-course.test.tsx
  src/widgets/about-course/ui/about-course/about-course.tsx
  src/widgets/about-video/ui/about-video.tsx
  src/widgets/communication/ui/communication.test.tsx
  src/widgets/communication/ui/communication.tsx
  src/widgets/hero-course/ui/hero-course.test.tsx
  src/widgets/hero-course/ui/hero-course.tsx
  src/widgets/member-activity/ui/member-activity.tsx
  src/widgets/mentors-wanted/ui/mentors-wanted.test.tsx
  src/widgets/mentors-wanted/ui/mentors-wanted.tsx
  src/widgets/school-menu/ui/school-menu/school-menu.test.tsx
  src/widgets/trainers/ui/trainers.test.tsx
  src/widgets/trainers/ui/trainers.tsx
  src/widgets/training-program/ui/training-program.test.tsx
  src/widgets/training-program/ui/training-program.tsx
Labels: preview

#683 650-feat: Add docs
  eslint.config.js
  package-lock.json
  package.json
  src/app/docs/[lang]/[...slug]/page.tsx
  src/app/docs/[lang]/page.tsx
  src/app/docs/components/docs-layout/docs-layout.module.scss
  src/app/docs/components/docs-layout/docs-layout.tsx
  src/app/docs/components/docs-menu/docs-menu.module.scss
  src/app/docs/components/docs-menu/docs-menu.tsx
  src/app/docs/components/lang-switcher/lang-switcher.module.scss
  src/app/docs/components/lang-switcher/lang-switcher.tsx
  src/app/docs/components/search/search.module.scss
  src/app/docs/components/search/search.tsx
  src/app/docs/components/search/types.ts
  src/app/docs/constants.ts
  src/app/docs/mocked_search.ts
  src/app/docs/types.ts
  src/app/docs/utils/fetchMarkdownContent.ts
  src/app/docs/utils/fetchMenu.ts
  src/core/base-layout/components/header/burger/burger.module.scss
  src/core/base-layout/components/header/header.module.scss
  src/core/base-layout/components/header/header.test.tsx
  src/core/base-layout/components/header/header.tsx
  src/core/base-layout/components/header/nav-item/nav-item.tsx
  src/core/const/index.ts
  src/core/styles/_constants.scss
  src/core/styles/index.scss
  src/core/types/route.types.ts
  src/shared/assets/svg/chevron-right.svg
  src/shared/assets/svg/link.svg
  src/shared/assets/svg/translate.svg
  src/shared/helpers/isValidUrl.ts
  src/widgets/mobile-view/ui/mobile-view.tsx
Labels: preview

#706 705-fix: Console warnings
  src/core/base-layout/components/header/nav-item/nav-item.tsx
  src/widgets/mobile-view/ui/mobile-view.tsx
Labels: bug, preview

#698 565-feat: Connect google analytics
  package-lock.json
  package.json
  src/app/analytics.tsx
  src/app/layout.tsx
Labels: preview

#733 410-feat: Add funding yml file
  .github/FUNDING.yml
Labels: good first issue, preview

#737 736-refactor: Update vitest eslint plugin
  eslint.config.js
  package-lock.json
  package.json
Labels: preview

#730 716-feat: Mentorship courses
  dev-data/index.ts
  dev-data/mentorship-data.types.ts
  next-env.d.ts
  src/app/mentorship/[course]/page.tsx
  src/app/mentorship/page.tsx
  src/entities/course/ui/course-card/course-card.tsx
  src/views/mentorship/constants.ts
  src/views/mentorship/helpers/transformCoursesToMentorship.ts
  src/views/mentorship/mentorship.tsx
  src/views/mentorship/ui/mentorship-courses/mentorship-courses.module.scss
  src/views/mentorship/ui/mentorship-courses/mentorship-courses.test.tsx
  src/views/mentorship/ui/mentorship-courses/mentorship-courses.tsx
Labels: feature, high priority, preview

#735 718-feat: Mentorship feedback video
  env.d.ts
  package-lock.json
  package.json
  readme/styleguide-design.md
  src/core/styles/_constants.scss
  src/core/styles/index.scss
  src/entities/course/ui/course-card/course-card.test.tsx
  src/entities/course/ui/course-card/course-card.tsx
  src/shared/__tests__/constants.ts
  src/shared/types.ts
  src/shared/ui/video-player/index.ts
  src/shared/ui/video-player/video-player.module.scss
  src/shared/ui/video-player/video-player.tsx
  src/shared/ui/video-playlist-with-player/index.ts
  src/shared/ui/video-playlist-with-player/playlist/index.ts
  src/shared/ui/video-playlist-with-player/playlist/playlist.module.scss
  src/shared/ui/video-playlist-with-player/playlist/playlist.test.tsx
  src/shared/ui/video-playlist-with-player/playlist/playlist.tsx
  src/shared/ui/video-playlist-with-player/video-playlist-with-player.module.scss
  src/shared/ui/video-playlist-with-player/video-playlist-with-player.test.tsx
  src/shared/ui/video-playlist-with-player/video-playlist-with-player.tsx
  src/views/mentorship/mentorship.tsx
  src/widgets/about-video/ui/about-video.module.scss
  src/widgets/about-video/ui/about-video.test.tsx
  src/widgets/about-video/ui/about-video.tsx
  src/widgets/mentors-feedback/index.ts
  src/widgets/mentors-feedback/ui/mentors-feedback.module.scss
  src/widgets/mentors-feedback/ui/mentors-feedback.tsx
  tsconfig.json
  vitest.config.ts
Labels: preview

#728 721-refactor: Mentorship redesign any other questions
  dev-data/mentorship.data.ts
  src/widgets/mentors-docs/ui/mentors-docs/mentors-docs.module.scss
  src/widgets/mentors-docs/ui/mentors-docs/mentors-docs.tsx
Labels: refactor, high priority

#744 Add missing github actions variable
  .github/workflows/main.yml
  .github/workflows/preview-create.yml
  .github/workflows/production.yml
  .github/workflows/visual-testing-on-comment.yml
  .github/workflows/visual-testing-on-push.yml
Labels: preview

#729 713-refactor: Hero section
  dev-data/hero-page.data.ts
  src/core/styles/_constants.scss
  src/shared/assets/mentorship-hero.webp
  src/shared/assets/photo-1.webp
  src/shared/ui/subtitle/subtitle.module.scss
  src/shared/ui/subtitle/subtitle.tsx
  src/views/mentorship/mentorship-hero/index.ts
  src/views/mentorship/mentorship-hero/ui/mentorship-hero.module.scss
  src/views/mentorship/mentorship-hero/ui/mentorship-hero.test.tsx
  src/views/mentorship/mentorship-hero/ui/mentorship-hero.tsx
  src/views/mentorship/mentorship.tsx
  src/widgets/hero-page/ui/hero-page.module.scss
  src/widgets/hero-page/ui/hero-page.tsx
Labels: preview

#748 720-refactor: After completing registration section
  dev-data/index.ts
  dev-data/mentors-after-register.data.ts
  dev-data/mentors-register.data.ts
  src/views/mentorship.tsx
  src/views/mentorship/ui/mentors-after-register/index.ts
  src/views/mentorship/ui/mentors-after-register/ui/mentors-after-register.module.scss
  src/views/mentorship/ui/mentors-after-register/ui/mentors-after-register.test.tsx
  src/views/mentorship/ui/mentors-after-register/ui/mentors-after-register.tsx
  src/widgets/mentors-register/ui/mentors-register.tsx
Labels: preview

#749 615-feat: Fix link custom
  src/shared/ui/link-custom/link-custom.module.scss
Labels: bug, good first issue, preview

#743 714-refactor: Mentorship Details Widget
  dev-data/about-mentors.data.ts
  dev-data/index.ts
  dev-data/mentorship-data.types.ts
  dev-data/mentorship.data.ts
  src/core/base-layout/components/header/header.module.scss
  src/core/styles/_constants.scss
  src/views/mentorship/mentorship.tsx
  src/views/mentorship/ui/details/details.module.scss
  src/views/mentorship/ui/details/details.test.tsx
  src/views/mentorship/ui/details/details.tsx
  src/widgets/numbers/ui/info-cell/info-cell.module.scss
  src/widgets/numbers/ui/info-cell/info-cell.test.tsx
  src/widgets/numbers/ui/info-cell/info-cell.tsx
  src/widgets/numbers/ui/info-grid/info-grid.module.scss
  src/widgets/numbers/ui/info-grid/info-grid.tsx
  src/widgets/numbers/ui/numbers/numbers.module.scss
  src/widgets/numbers/ui/numbers/numbers.tsx
Labels: refactor, high priority, preview

#731 719-refactor: Mentorship redesign register as a mentor section
  dev-data/mentor-docs.data.ts
  dev-data/mentors-register.data.ts
  src/core/base-layout/components/header/header.module.scss
  src/core/styles/_constants.scss
  src/shared/assets/mentor-register.svg
  src/views/mentorship/ui/details/details.module.scss
  src/widgets/mentors-docs/ui/doc-detail/ui/doc-detail.tsx
  src/widgets/mentors-register/ui/mentors-register.module.scss
  src/widgets/mentors-register/ui/mentors-register.test.tsx
  src/widgets/mentors-register/ui/mentors-register.tsx
Labels: refactor, high priority, preview

#759 715-refactor: Mentor activities
  dev-data/courses-data.types.ts
  dev-data/index.ts
  dev-data/mentorship-data.types.ts
  dev-data/mentorship.data.ts
  src/core/styles/_constants.scss
  src/shared/assets/svg/best-practices-icon.svg
  src/shared/assets/svg/code-review-icon.svg
  src/shared/assets/svg/conducting-tech-interview-icon.svg
  src/shared/assets/svg/supervising-team-assignment-icon.svg
  src/views/mentorship/mentorship.tsx
  src/views/mentorship/ui/mentor-activities/index.ts
  src/views/mentorship/ui/mentor-activities/ui/activity-card/activity-card.module.scss
  src/views/mentorship/ui/mentor-activities/ui/activity-card/activity-card.test.tsx
  src/views/mentorship/ui/mentor-activities/ui/activity-card/activity-card.tsx
  src/views/mentorship/ui/mentor-activities/ui/mentor-activities/mentor-activities.module.scss
  src/views/mentorship/ui/mentor-activities/ui/mentor-activities/mentor-activities.test.tsx
  src/views/mentorship/ui/mentor-activities/ui/mentor-activities/mentor-activities.tsx
  src/widgets/member-activity/ui/member-activity.tsx
Labels: preview

#757 738-fix: Logo shrinking on small screens
  src/core/base-layout/components/header/burger/burger.module.scss
  src/core/base-layout/components/header/header.module.scss
  src/shared/ui/logo/logo.module.scss
  src/widgets/mobile-view/ui/mobile-view.module.scss
Labels: preview

#760 fix/issue-with-course-links
  src/views/mentorship/helpers/transformCoursesToMentorship.ts
Labels: preview

#762 761-fix: Filter out private videos on mentorship page
  src/shared/ui/video-playlist-with-player/constants.ts
  src/shared/ui/video-playlist-with-player/video-playlist-with-player.test.tsx
  src/shared/ui/video-playlist-with-player/video-playlist-with-player.tsx
Labels: bug, high priority, preview

#726 725-feat: Sync wearecommunity link with api data
  dev-data/about-course.data.tsx
  dev-data/courses.data.ts
  dev-data/hero-course.data.ts
  dev-data/training-program.data.tsx
  src/core/styles/_constants.scss
  src/entities/course/helpers/sync-with-api-data.ts
  src/entities/course/types.ts
  src/shared/__tests__/constants.ts
  src/shared/constants.ts
  src/shared/ui/link-custom/link-custom.module.scss
  src/shared/ui/link-custom/link-custom.tsx
  src/widgets/about-course/ui/about-course/about-course.test.tsx
  src/widgets/about-course/ui/about-course/about-course.tsx
  src/widgets/hero-course/ui/hero-course.test.tsx
  src/widgets/hero-course/ui/hero-course.tsx
  src/widgets/training-program/ui/training-program.test.tsx
  src/widgets/training-program/ui/training-program.tsx
Labels: feature, preview

#766 764-refactor: Update team description
  dev-data/react-en.data.ts
Labels: refactor, preview
